In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as st

import warnings

folder='D:/Data_Analyst_Projet/Projet 5/Donnees/Donnees analyse python/'

In [6]:
warnings.simplefilter("ignore")
erp=pd.read_excel(folder+'erp.xlsx')
erp.head()

   product_id  onsale_web  price  stock_quantity stock_status
0        3847           1   24.2               0   outofstock
1        3849           1   34.3               0   outofstock
2        3850           1   20.8               0   outofstock
3        4032           1   14.1               0   outofstock
4        4039           1   46.0               0   outofstock

In [10]:
from fonctions import *

In [11]:
stat_var(erp['price'])

,echantillon_base,echantillon_base_IQR,echantillon_base_zscore,echantillon_base_log,log_IQR,log_zscore
moyenne,32.42,28.26,29.88,3.22,3.15,3.18
moyenne_min,29.17,25.43,26.89,2.9,2.84,2.87
moyenne_max,35.66,31.08,32.86,3.55,3.47,3.5
test_moyenne_10_%,False,False,False,True,True,True
mediane,24.4,23.4,24.0,3.19,3.15,3.18
mode,45.0,45.0,45.0,3.81,3.81,3.81
moyenne_tronquee,29.14,26.98,28.02,3.21,3.16,3.18
ecart_type,26.8,17.52,20.27,0.7,0.63,0.66
CV,0.83,0.62,0.68,0.22,0.2,0.21
IQR,27.4,24.72,25.8,1.06,1.01,1.03
skewness,2.62,1.0,1.36,0.24,-0.05,0.05
skewness_pvalue,0.0,0.0,0.0,0.004374,0.581792,0.580995
kurtosis,10.62,0.29,1.8,-0.34,-0.8,-0.7
kurtosis_pvalue,0.0,0.122684,0.0,0.01806,0.0,0.0
ks_pvalue,0.0,0.0,0.0,0.0,0.0,0.0
shapiro_pvalue,0.0,0.0,0.0,0.0,0.0,0.0