In [3]:
# Import des librairies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import re
import time

import psycopg2

from sqlalchemy import create_engine, inspect
from sqlalchemy import DATE, DATETIME, FLOAT, VARCHAR, INTEGER, DateTime

import xml.etree.ElementTree as ET
from inspect import getmembers, isclass, isfunction

from sklearn.preprocessing import LabelEncoder

In [4]:
from tqdm import tqdm

In [5]:
pd.set_option('display.max_row', 200)
pd.set_option('display.max_columns', 50)

In [6]:
folder = 'D:/Fichiers_dev/test_xml/'
folder_export = 'D:/Fichiers_dev/test_xml/tables/'

## Initialisation des objets

In [7]:
# xml en tant qu'objet arborescence
# représente la structure hiérarchique complète de l'arbre XML
tree = ET.parse(folder + 'declarations.xml')

In [8]:
# element racine de l'arbre xml, objet Element
# c'est à partir de cet objet qu'on manipule le xml
root = tree.getroot()

## Création du script de traitement du xml

In [9]:
def scan_xml(root):
    # script de scan du xml
    for element, i in zip(root, range(len(root))):

        for enfant in element:
            chemin_complet_niv1 = element.tag + '/' + enfant.tag
            champs_niv1 = enfant.tag
            valeur_niv1 = enfant.text
            niveau = 1
            #print(chemin_complet_niv1, champs_niv1, valeur_niv1)

            uuid = root[i].findall('uuid')[0].text

            if valeur_niv1 : 

                uuids.append(uuid)
                chemins.append(chemin_complet_niv1)
                champss.append(champs_niv1)
                valeurs.append(valeur_niv1)
                niveaux.append(niveau)


            for enfant_niv2 in enfant:
                chemin_complet_niv2 = chemin_complet_niv1 + '/' + enfant_niv2.tag
                champs_niv2 = enfant_niv2.tag
                valeur_niv2 = enfant_niv2.text
                niveau = 2
                #print(chemin_complet_niv2, champs_niv2, valeur_niv2)

                if valeur_niv2 : 

                    uuids.append(uuid)
                    chemins.append(chemin_complet_niv2)
                    champss.append(champs_niv2)
                    valeurs.append(valeur_niv2)
                    niveaux.append(niveau)


                for enfant_niv3 in enfant_niv2:
                    chemin_complet_niv3 = chemin_complet_niv2 + '/' + enfant_niv3.tag
                    champs_niv3 = enfant_niv3.tag
                    valeur_niv3 = enfant_niv3.text
                    niveau = 3
                    #print(chemin_complet_niv3, champs_niv3, valeur_niv3)

                    if valeur_niv3 : 

                        uuids.append(uuid)
                        chemins.append(chemin_complet_niv3)
                        champss.append(champs_niv3)
                        valeurs.append(valeur_niv3)
                        niveaux.append(niveau)

                    for enfant_niv4 in enfant_niv3:
                        chemin_complet_niv4 = chemin_complet_niv3 + '/' + enfant_niv4.tag
                        champs_niv4 = enfant_niv4.tag
                        valeur_niv4 = enfant_niv4.text
                        niveau = 4
                        #print(chemin_complet_niv4, champs_niv4, valeur_niv4)      

                        if valeur_niv4 : 

                            uuids.append(uuid)
                            chemins.append(chemin_complet_niv4)
                            champss.append(champs_niv4)
                            valeurs.append(valeur_niv4)
                            niveaux.append(niveau)


                        for enfant_niv5 in enfant_niv4:
                            chemin_complet_niv5 = chemin_complet_niv4 + '/' + enfant_niv5.tag
                            champs_niv5 = enfant_niv5.tag
                            valeur_niv5 = enfant_niv5.text
                            niveau = 5
                            #print(chemin_complet_niv5, champs_niv5, valeur_niv5)   

                            if valeur_niv5 : 

                                uuids.append(uuid)
                                chemins.append(chemin_complet_niv5)
                                champss.append(champs_niv5)
                                valeurs.append(valeur_niv5)
                                niveaux.append(niveau)

                            for enfant_niv6 in enfant_niv5:
                                chemin_complet_niv6 = chemin_complet_niv5 + '/' + enfant_niv6.tag
                                champs_niv6 = enfant_niv6.tag
                                valeur_niv6 = enfant_niv6.text
                                niveau = 6
                                #print(chemin_complet_niv6, champs_niv6, valeur_niv6)   

                                if valeur_niv6 : 

                                    uuids.append(uuid)
                                    chemins.append(chemin_complet_niv6)
                                    champss.append(champs_niv6)
                                    valeurs.append(valeur_niv6)    
                                    niveaux.append(niveau)


                                for enfant_niv7 in enfant_niv6:
                                    chemin_complet_niv7 = chemin_complet_niv6 + '/' + enfant_niv7.tag
                                    champs_niv7 = enfant_niv7.tag
                                    valeur_niv7 = enfant_niv7.text
                                    niveau = 7
                                    #print(chemin_complet_niv7, champs_niv7, valeur_niv7) 

                                    if valeur_niv7 : 

                                        uuids.append(uuid)
                                        chemins.append(chemin_complet_niv7)
                                        champss.append(champs_niv7)
                                        valeurs.append(valeur_niv7)  
                                        niveaux.append(niveau)

                                    for enfant_niv8 in enfant_niv7:
                                        chemin_complet_niv8 = chemin_complet_niv7 + '/' + enfant_niv8.tag
                                        champs_niv8 = enfant_niv8.tag
                                        valeur_niv8 = enfant_niv8.text
                                        niveau = 8
                                        #print(chemin_complet_niv8, champs_niv8, valeur_niv8) 

                                        if valeur_niv8 : 

                                            uuids.append(uuid)
                                            chemins.append(chemin_complet_niv8)
                                            champss.append(champs_niv8)
                                            valeurs.append(valeur_niv8)  
                                            niveaux.append(niveau)

In [10]:
print(f"L'arbre contient {len(root)} déclarations.")

L'arbre contient 10893 déclarations.

In [11]:
# creation des listes de stockage
uuids = []
chemins = []
champss = []
valeurs = []
niveaux = []

start_time = time.time()

scan_xml(root)

dictionnaire = {
    'id_declaration' : uuids,
    'chemins' : chemins,
    'champs' : champss,
    'valeurs' : valeurs,
    'niveaux' : niveaux
}

data = pd.DataFrame(dictionnaire)

end_time = time.time()

temps_execution1 = end_time - start_time

print(f"Le temps d'execution est de {temps_execution1}")

print(f"{data.shape[0]} lignes, {data.shape[1]} colonnes.")

Le temps d'execution est de 5.141042947769165
3010356 lignes, 5 colonnes.

## Création du Dataframe

In [12]:
data.head(100)

,id_declaration,chemins,champs,valeurs,niveaux
0,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/dateDepot,dateDepot,11/07/2022 15:40:13,1
1,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/uuid,uuid,4344aaa1-874d-4e6d-9b1a-45f7725b710c,1
2,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/origine,origine,ADEL,1
3,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/complete,complete,true,1
4,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/attachedFiles,attachedFiles,\n\t\t\t,1
5,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/attachedFiles/attachedFiles,attachedFiles,\n\t\t\t\t,2
6,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/attachedFiles/attachedFiles/fileName,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML,3
7,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/declarationVersion,declarationVersion,20171221,1
8,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activConsultantDto,activConsultantDto,\n\t\t\t,1
9,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activConsultantDto/neant,neant,true,2
10,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfCinqDerniereDto,activProfCinqDerniereDto,\n\t\t\t,1
11,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfCinqDerniereDto/neant,neant,true,2
12,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto,activProfConjointDto,\n\t\t\t,1
13,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items,items,\n\t\t\t\t,2
14,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items,items,\n\t\t\t\t\t,3
15,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items/m...,motif,\n\t\t\t\t\t\t,4
16,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items/m...,id,CREATION,5
17,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items/n...,nomConjoint,\n [Données non publiées]\n,4
18,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items/e...,employeurConjoint,CENTRE HOSPITALIER DU HAUT-BUGEY,4
19,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items/a...,activiteProf,Infirmière,4
20,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/neant,neant,false,2
21,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/fonctionBenevoleDto,fonctionBenevoleDto,\n\t\t\t,1
22,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/fonctionBenevoleDto/neant,neant,true,2
23,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto,mandatElectifDto,\n\t\t\t,1
24,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items,items,\n\t\t\t\t,2
25,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items,items,\n\t\t\t\t\t,3
26,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif,motif,\n\t\t\t\t\t\t,4
27,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif/id,id,CREATION,5
28,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/comme...,commentaire,REVENUS NETS IMPOSABLES\n [Données non ...,4
29,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/descr...,descriptionMandat,DEPUTE,4
30,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,remuneration,\n\t\t\t\t\t\t,4
31,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,brutNet,Net,5
32,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t,5
33,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
34,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2017,7
35,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,67 047,7
36,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
37,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2018,7
38,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,71 042,7
39,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
40,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2019,7
41,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,71 105,7
42,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
43,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2020,7
44,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,70 773,7
45,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
46,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2021,7
47,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,70 676,7
48,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
49,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2022,7
50,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,27 289,7
51,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateD...,dateDebut,01/2017,4
52,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items,items,\n\t\t\t\t\t,3
53,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif,motif,\n\t\t\t\t\t\t,4
54,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif/id,id,CREATION,5
55,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/comme...,commentaire,REVENUS NETS IMPOSABLES\n [Données non ...,4
56,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/descr...,descriptionMandat,PRESIDENT DU DEPARTEMENT 01,4
57,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,remuneration,\n\t\t\t\t\t\t,4
58,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,brutNet,Net,5
59,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t,5
60,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
61,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2015,7
62,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,16865,7
63,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
64,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2016,7
65,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,23035,7
66,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
67,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2017,7
68,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,20120,7
69,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateD...,dateDebut,04/2015,4
70,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateFin,dateFin,07/2017,4
71,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items,items,\n\t\t\t\t\t,3
72,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif,motif,\n\t\t\t\t\t\t,4
73,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif/id,id,CREATION,5
74,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/comme...,commentaire,J'ai été élu président de groupe LR le 6 Novem...,4
75,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/descr...,descriptionMandat,Président du Groupe Les Républicains à l'Assem...,4
76,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,remuneration,\n\t\t\t\t\t\t,4
77,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,brutNet,Net,5
78,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t,5
79,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
80,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2019,7
81,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
82,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
83,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2020,7
84,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
85,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
86,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2021,7
87,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
88,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,\n\t\t\t\t\t\t\t\t,6
89,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2022,7
90,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
91,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateD...,dateDebut,11/2019,4
92,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateFin,dateFin,05/2022,4
93,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items,items,\n\t\t\t\t\t,3
94,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif,motif,\n\t\t\t\t\t\t,4
95,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif/id,id,CREATION,5
96,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/comme...,commentaire,\n [Données non publiées]\n,4
97,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/descr...,descriptionMandat,CONSEILLER DEPARTEMENTAL,4
98,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,remuneration,\n\t\t\t\t\t\t,4
99,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,brutNet,Net,5

In [13]:
data.shape

(3010356, 5)

## Nettoyage du tableau

In [14]:
# nettoyage des valeurs tabulation "\t"
data = data.drop(data[data['valeurs'].str.contains('\t')].index)
data.head(100)

,id_declaration,chemins,champs,valeurs,niveaux
0,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/dateDepot,dateDepot,11/07/2022 15:40:13,1
1,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/uuid,uuid,4344aaa1-874d-4e6d-9b1a-45f7725b710c,1
2,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/origine,origine,ADEL,1
3,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/complete,complete,true,1
6,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/attachedFiles/attachedFiles/fileName,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML,3
7,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/declarationVersion,declarationVersion,20171221,1
9,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activConsultantDto/neant,neant,true,2
11,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfCinqDerniereDto/neant,neant,true,2
16,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items/m...,id,CREATION,5
17,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items/n...,nomConjoint,\n [Données non publiées]\n,4
18,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items/e...,employeurConjoint,CENTRE HOSPITALIER DU HAUT-BUGEY,4
19,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/items/items/a...,activiteProf,Infirmière,4
20,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/activProfConjointDto/neant,neant,false,2
22,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/fonctionBenevoleDto/neant,neant,true,2
27,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif/id,id,CREATION,5
28,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/comme...,commentaire,REVENUS NETS IMPOSABLES\n [Données non ...,4
29,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/descr...,descriptionMandat,DEPUTE,4
31,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,brutNet,Net,5
34,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2017,7
35,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,67 047,7
37,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2018,7
38,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,71 042,7
40,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2019,7
41,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,71 105,7
43,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2020,7
44,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,70 773,7
46,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2021,7
47,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,70 676,7
49,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2022,7
50,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,27 289,7
51,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateD...,dateDebut,01/2017,4
54,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif/id,id,CREATION,5
55,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/comme...,commentaire,REVENUS NETS IMPOSABLES\n [Données non ...,4
56,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/descr...,descriptionMandat,PRESIDENT DU DEPARTEMENT 01,4
58,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,brutNet,Net,5
61,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2015,7
62,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,16865,7
64,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2016,7
65,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,23035,7
67,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2017,7
68,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,20120,7
69,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateD...,dateDebut,04/2015,4
70,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateFin,dateFin,07/2017,4
73,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif/id,id,CREATION,5
74,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/comme...,commentaire,J'ai été élu président de groupe LR le 6 Novem...,4
75,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/descr...,descriptionMandat,Président du Groupe Les Républicains à l'Assem...,4
77,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,brutNet,Net,5
80,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2019,7
81,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
83,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2020,7
84,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
86,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2021,7
87,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
89,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2022,7
90,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
91,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateD...,dateDebut,11/2019,4
92,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateFin,dateFin,05/2022,4
95,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif/id,id,CREATION,5
96,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/comme...,commentaire,\n [Données non publiées]\n,4
97,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/descr...,descriptionMandat,CONSEILLER DEPARTEMENTAL,4
99,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,brutNet,Net,5
102,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2017,7
103,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,28 007,7
105,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2018,7
106,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,24 201,7
108,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2019,7
109,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,16 386,7
111,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2020,7
112,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,16 386,7
114,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2021,7
115,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,16 384,7
117,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2022,7
118,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,6 827,7
119,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateD...,dateDebut,07/2017,4
122,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/motif/id,id,CREATION,5
123,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/descr...,descriptionMandat,Département de l'Ain - Président du Groupe maj...,4
125,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,brutNet,Net,5
128,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2017,7
129,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
131,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2018,7
132,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
134,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2019,7
135,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
137,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2020,7
138,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
140,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2021,7
141,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
143,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,annee,2022,7
144,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/remun...,montant,0,7
145,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/items/items/dateD...,dateDebut,07/2017,4
146,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/mandatElectifDto/neant,neant,false,2
151,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/participationDirigeantDto/items/it...,id,CREATION,5
152,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/participationDirigeantDto/items/it...,commentaire,Président du SDIS 01. Activité arrêtée depuis ...,4
153,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/participationDirigeantDto/items/it...,nomSociete,SDIS 01,4
154,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/participationDirigeantDto/items/it...,activite,Service départemental d'incendie et de secours,4
156,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/participationDirigeantDto/items/it...,brutNet,Brut,5
159,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/participationDirigeantDto/items/it...,annee,2015,7
160,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/participationDirigeantDto/items/it...,montant,0,7
162,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/participationDirigeantDto/items/it...,annee,2016,7
163,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration/participationDirigeantDto/items/it...,montant,0,7

In [15]:
data.shape

(1944263, 5)

In [16]:
# pour toutes les valeurs qui contiennent '\n', efface les '\n' puis supprime les espaces au début et à la fin de la chaine
data.loc[data['valeurs'].str.contains('\n'), 'valeurs'] = data.loc[data['valeurs'].str.contains('\n'),
                                                                   'valeurs'].str.replace('\n', '').str.strip()

In [17]:
# suppression des champs en base 64, chemins ou il y a 'b64'
data = data.drop(data[data['chemins'].str.contains('b64')].index)
data = data.drop(data[data['chemins'].str.contains('base64')].index)

In [18]:
data.shape

(1944208, 5)

#### Fonction modif champs format table

In [19]:
def modif_champs(valeur):
    ''' Fonction qui modifie les champs pour pouvoir les utiliser comme champs de base de données sans avoir d'erreurs.
    - remplace les "/" par des "_", 
    - ajoute un "_" avant les majuscules,
    - transforme le tout en minuscule.'''
    
    valeur = re.sub(r'([A-Z])', r'_\1', valeur)
    valeur = valeur.lower()
    
    return valeur

In [20]:
print(modif_champs.__doc__)

 Fonction qui modifie les champs pour pouvoir les utiliser comme champs de base de données sans avoir d'erreurs.
    - remplace les "/" par des "_",
    - ajoute un "_" avant les majuscules,
    - transforme le tout en minuscule.

#### Modification chemins

In [21]:
# creation chemin
data['chemins'] = data['chemins'].str.replace('declaration/', '')

In [22]:
data.head()

,id_declaration,chemins,champs,valeurs,niveaux
0,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDepot,dateDepot,11/07/2022 15:40:13,1
1,4344aaa1-874d-4e6d-9b1a-45f7725b710c,uuid,uuid,4344aaa1-874d-4e6d-9b1a-45f7725b710c,1
2,4344aaa1-874d-4e6d-9b1a-45f7725b710c,origine,origine,ADEL,1
3,4344aaa1-874d-4e6d-9b1a-45f7725b710c,complete,complete,true,1
6,4344aaa1-874d-4e6d-9b1a-45f7725b710c,attachedFiles/attachedFiles/fileName,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML,3

#### Ajout du nombre d'occurences
pour identifier les champs recurrents et rares

In [23]:
nombre_occurence = data['chemins'].value_counts().reset_index().rename(columns={'chemins':'nombre_occurence',
                                                                                  'index':'chemins'})

#### Suppression des doublons

In [24]:
#data = data.drop(data[data.duplicated(subset=['id_declaration', 'chemins', 'valeurs'])].index)
# supprime les Id des mandats

In [25]:
# merge avec occurence
#data3 = pd.merge(data, nombre_occurence, how='left', left_on='chemins', right_on='chemins')
#data3.head()

In [26]:
data3 = data[['id_declaration', 'chemins', 'champs', 'valeurs']]

In [27]:
data3

,id_declaration,chemins,champs,valeurs
0,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDepot,dateDepot,11/07/2022 15:40:13
1,4344aaa1-874d-4e6d-9b1a-45f7725b710c,uuid,uuid,4344aaa1-874d-4e6d-9b1a-45f7725b710c
2,4344aaa1-874d-4e6d-9b1a-45f7725b710c,origine,origine,ADEL
3,4344aaa1-874d-4e6d-9b1a-45f7725b710c,complete,complete,true
6,4344aaa1-874d-4e6d-9b1a-45f7725b710c,attachedFiles/attachedFiles/fileName,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
...,...,...,...,...
3010351,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/voie,voie,[Données non publiées]
3010352,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/complement,complement,[Données non publiées]
3010353,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/codePostal,codePostal,[Données non publiées]
3010354,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/ville,ville,[Données non publiées]
3010355,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/pays,pays,[Données non publiées]

### Export dans excel des chemins uniques

In [26]:
#chemins_excel = data[['chemins', 'champs']].drop_duplicates(subset='chemins')

#chemins_excel.to_excel(folder + 'chemins_uniques.xlsx')

#chemins_excel.shape

## Création des tables

In [27]:
data3.shape

(1944208, 4)

## Table individus

In [28]:
mask_colonne_table_individus = (data3['chemins'].str.contains('general/declarant/'))

In [29]:
individus = data3[mask_colonne_table_individus]

In [30]:
individus = individus[['id_declaration', 'champs', 'valeurs']]
individus

,id_declaration,champs,valeurs
352,4344aaa1-874d-4e6d-9b1a-45f7725b710c,civilite,M.
353,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nom,ABAD
354,4344aaa1-874d-4e6d-9b1a-45f7725b710c,prenom,DAMIEN
355,4344aaa1-874d-4e6d-9b1a-45f7725b710c,email,[Données non publiées]
356,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateNaissance,05/04/1980
...,...,...,...
3010351,d1129c22-a715-4df6-8c0f-cfc678f1518c,voie,[Données non publiées]
3010352,d1129c22-a715-4df6-8c0f-cfc678f1518c,complement,[Données non publiées]
3010353,d1129c22-a715-4df6-8c0f-cfc678f1518c,codePostal,[Données non publiées]
3010354,d1129c22-a715-4df6-8c0f-cfc678f1518c,ville,[Données non publiées]
3010355,d1129c22-a715-4df6-8c0f-cfc678f1518c,pays,[Données non publiées]

In [31]:
# suppression des declarations/individus en doublons, suppression des lignes si pour une meme declaration plusieurs individus mentionnés
# on gardera les dernières valeurs
individus = individus.drop(individus[individus.duplicated(subset=['id_declaration', 'champs'], keep='last')].index)

In [32]:
# pivot des champs
individus = pd.pivot(individus, columns='champs', index='id_declaration', values='valeurs').reset_index()

In [33]:
individus['id_individu'] = individus['nom']+individus['prenom']+individus['dateNaissance']
individus

champs,id_declaration,civilite,codePostal,complement,dateNaissance,email,nom,pays,prenom,telephoneDec,ville,voie,id_individu
0,000765d9-da68-48c6-a95d-f34a12cacb5f,M.,[Données non publiées],[Données non publiées],29/07/1951,[Données non publiées],DELAPORTE,[Données non publiées],Olivier,[Données non publiées],[Données non publiées],[Données non publiées],DELAPORTEOlivier29/07/1951
1,00138e83-44ec-4da1-89f3-37d2309a62a2,Mme,[Données non publiées],[Données non publiées],04/04/1964,[Données non publiées],SCHMITT,[Données non publiées],SYLVIE,[Données non publiées],[Données non publiées],[Données non publiées],SCHMITTSYLVIE04/04/1964
2,0014115c-cbae-4bdd-98d1-39c8e6062095,M.,[Données non publiées],[Données non publiées],26/06/1946,[Données non publiées],PELIEU,[Données non publiées],MICHEL,[Données non publiées],[Données non publiées],[Données non publiées],PELIEUMICHEL26/06/1946
3,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,Mme,[Données non publiées],[Données non publiées],14/03/1953,[Données non publiées],Gatel,[Données non publiées],Françoise,[Données non publiées],[Données non publiées],[Données non publiées],GatelFrançoise14/03/1953
4,00243ad5-2191-4efc-884b-df9213413b17,Mme,[Données non publiées],[Données non publiées],30/11/1963,[Données non publiées],lecordier,[Données non publiées],nathalie,[Données non publiées],[Données non publiées],[Données non publiées],lecordiernathalie30/11/1963
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10869,ffe77ec2-bc2d-495c-9240-e9e05d0ebccc,M.,[Données non publiées],[Données non publiées],20/03/1967,[Données non publiées],Kermorvant,[Données non publiées],Patrice,[Données non publiées],[Données non publiées],[Données non publiées],KermorvantPatrice20/03/1967
10870,ffe864c3-aaa8-4218-837c-003c6024017e,Mme,[Données non publiées],[Données non publiées],01/12/1970,[Données non publiées],Grignola-Bernard,[Données non publiées],Virginie,[Données non publiées],[Données non publiées],[Données non publiées],Grignola-BernardVirginie01/12/1970
10871,ffe8cb24-2c74-4f7d-a734-78011e1937d2,M.,[Données non publiées],[Données non publiées],29/10/1980,[Données non publiées],BLINT,[Données non publiées],Cyrille,[Données non publiées],[Données non publiées],[Données non publiées],BLINTCyrille29/10/1980
10872,ffeaea0a-543e-429c-8808-daeb77410cc2,Mme,[Données non publiées],[Données non publiées],23/02/1964,[Données non publiées],DEZARNAUD,[Données non publiées],Sylvie,[Données non publiées],[Données non publiées],[Données non publiées],DEZARNAUDSylvie23/02/1964
10873,ffebc082-9175-45a5-be14-da1a3d89e87e,Mme,[Données non publiées],[Données non publiées],26/03/1950,[Données non publiées],Mélin,[Données non publiées],Joëlle,[Données non publiées],[Données non publiées],[Données non publiées],MélinJoëlle26/03/1950

In [34]:
individus.shape

(10874, 13)

In [35]:
# suppression des doublons
individus = individus.drop_duplicates('id_individu').drop(columns='id_declaration').reset_index(drop=True)
individus.head()

champs,civilite,codePostal,complement,dateNaissance,email,nom,pays,prenom,telephoneDec,ville,voie,id_individu
0,M.,[Données non publiées],[Données non publiées],29/07/1951,[Données non publiées],DELAPORTE,[Données non publiées],Olivier,[Données non publiées],[Données non publiées],[Données non publiées],DELAPORTEOlivier29/07/1951
1,Mme,[Données non publiées],[Données non publiées],04/04/1964,[Données non publiées],SCHMITT,[Données non publiées],SYLVIE,[Données non publiées],[Données non publiées],[Données non publiées],SCHMITTSYLVIE04/04/1964
2,M.,[Données non publiées],[Données non publiées],26/06/1946,[Données non publiées],PELIEU,[Données non publiées],MICHEL,[Données non publiées],[Données non publiées],[Données non publiées],PELIEUMICHEL26/06/1946
3,Mme,[Données non publiées],[Données non publiées],14/03/1953,[Données non publiées],Gatel,[Données non publiées],Françoise,[Données non publiées],[Données non publiées],[Données non publiées],GatelFrançoise14/03/1953
4,Mme,[Données non publiées],[Données non publiées],30/11/1963,[Données non publiées],lecordier,[Données non publiées],nathalie,[Données non publiées],[Données non publiées],[Données non publiées],lecordiernathalie30/11/1963

In [36]:
individus.shape

(5869, 12)

In [37]:
# encodage id_individus
encoder_id_individu = LabelEncoder()

individus['id_individu'] = encoder_id_individu.fit_transform(individus['id_individu'])

In [38]:
# export en csv
individus.to_csv(folder_export + 'individus.csv', index=False)

## Table déclarations

In [39]:
# champs de la table en cours
champs_declaration = pd.read_excel(folder + 'chemins_uniques_2.xlsx', sheet_name='declarations')
champs_declaration = champs_declaration['champs'].str.replace('declaration/',"").values
champs_declaration

array(['complete', 'dateDepot', 'declarationVersion',
       'evenementMajeurDto/neant', 'general/chiffreAffaire',
       'general/dateDebutMandat', 'general/declarationModificative',
       'general/mandat/label', 'general/nomSociete',
       'general/nomSocieteMere', 'general/organe/codeListeOrgane',
       'general/organe/codeOrgane', 'general/organe/labelDeclaration',
       'general/organe/labelOrgane', 'general/organe/nomListeOrgane',
       'general/organe/organeParent', 'general/qualiteDeclarant',
       'general/qualiteDeclarantForPDF',
       'general/qualiteMandat/codCategorieMandat',
       'general/qualiteMandat/codeListeOrgane',
       'general/qualiteMandat/codTypeMandatFichier',
       'general/qualiteMandat/labelOrgane',
       'general/qualiteMandat/labelTypeMandat',
       'general/qualiteMandat/nomCategorieMandat',
       'general/qualiteMandat/typeMandat', 'general/regimeMatrimonial',
       'general/regimeMatrimonialComments', 'general/typeDeclaration/id',
       'general/typeDeclaration/label', 'origine',
       'revenuMandatDto/neant', 'uuid', 'general/declarant/dateNaissance',
       'general/declarant/nom', 'general/declarant/prenom',
       'activCollaborateursDto/neant', 'activConsultantDto/neant',
       'activProfCinqDerniereDto/neant', 'activProfConjointDto/neant',
       'assuranceVieDto/neant', 'autreBienDto/neant',
       'bienDiverDto/neant', 'bienEtrangerDto/neant',
       'comptesBancaireDto/neant', 'fonctionBenevoleDto/neant',
       'fondDto/neant', 'immeubleDto/neant', 'mandatElectifDto/neant',
       'observationInteretDto/neant', 'observationPatrimoineDto/neant',
       'participationDirigeantDto/neant',
       'participationFinanciereDto/neant', 'passifDto/neant',
       'sciDto/neant', 'valeursEnBourseDto/neant',
       'valeursNonEnBourseDto/neant', 'vehiculeDto/neant'], dtype=object)

In [40]:
declarations = data3.copy()
declarations.head()

,id_declaration,chemins,champs,valeurs
0,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDepot,dateDepot,11/07/2022 15:40:13
1,4344aaa1-874d-4e6d-9b1a-45f7725b710c,uuid,uuid,4344aaa1-874d-4e6d-9b1a-45f7725b710c
2,4344aaa1-874d-4e6d-9b1a-45f7725b710c,origine,origine,ADEL
3,4344aaa1-874d-4e6d-9b1a-45f7725b710c,complete,complete,true
6,4344aaa1-874d-4e6d-9b1a-45f7725b710c,attachedFiles/attachedFiles/fileName,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML

In [41]:
# mask de la table déclaration, mapping entre les champs de la table et le chemin xml
mask_declaration = declarations['chemins'].isin(champs_declaration)

In [42]:
declarations = declarations[mask_declaration][['id_declaration', 'chemins', 'valeurs']]
declarations.head()

,id_declaration,chemins,valeurs
0,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDepot,11/07/2022 15:40:13
1,4344aaa1-874d-4e6d-9b1a-45f7725b710c,uuid,4344aaa1-874d-4e6d-9b1a-45f7725b710c
2,4344aaa1-874d-4e6d-9b1a-45f7725b710c,origine,ADEL
3,4344aaa1-874d-4e6d-9b1a-45f7725b710c,complete,true
7,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declarationVersion,20171221

In [28]:
def modif_chemins_declaration(valeur):
    ''' Fonction qui modifie les chemins pour pouvoir les utiliser comme champs de base de données sans avoir d'erreurs.
    - retire 'general/',
    - remplace les "/" par des "_", 
    - ajoute un "_" avant les majuscules,
    - transforme le tout en minuscule.'''
    
    valeur = valeur.replace('general/','')
    valeur = valeur.replace('/','_')
    valeur = re.sub(r'([A-Z])', r'_\1', valeur)
    valeur = valeur.lower()
    
    return valeur

In [44]:
# modification du chemin avec la fonction modif_chemins_declaration
declarations['chemins'] = declarations['chemins'].apply(modif_chemins_declaration)

In [45]:
declarations.head()

,id_declaration,chemins,valeurs
0,4344aaa1-874d-4e6d-9b1a-45f7725b710c,date_depot,11/07/2022 15:40:13
1,4344aaa1-874d-4e6d-9b1a-45f7725b710c,uuid,4344aaa1-874d-4e6d-9b1a-45f7725b710c
2,4344aaa1-874d-4e6d-9b1a-45f7725b710c,origine,ADEL
3,4344aaa1-874d-4e6d-9b1a-45f7725b710c,complete,true
7,4344aaa1-874d-4e6d-9b1a-45f7725b710c,declaration_version,20171221

In [46]:
# suppression des doublons
declarations = declarations.drop(declarations[declarations.duplicated(subset=['id_declaration', 'chemins'],
                                                                      keep='last')].index)

In [47]:
# pivot des champs
declarations = declarations.pivot(index='id_declaration', columns='chemins', values='valeurs').reset_index()
declarations.head()

chemins,id_declaration,activ_collaborateurs_dto_neant,activ_consultant_dto_neant,activ_prof_cinq_derniere_dto_neant,activ_prof_conjoint_dto_neant,assurance_vie_dto_neant,autre_bien_dto_neant,bien_diver_dto_neant,bien_etranger_dto_neant,chiffre_affaire,complete,comptes_bancaire_dto_neant,date_debut_mandat,date_depot,declarant_date_naissance,declarant_nom,declarant_prenom,declaration_modificative,declaration_version,evenement_majeur_dto_neant,fonction_benevole_dto_neant,fond_dto_neant,immeuble_dto_neant,mandat_electif_dto_neant,mandat_label,...,organe_nom_liste_organe,organe_organe_parent,origine,participation_dirigeant_dto_neant,participation_financiere_dto_neant,passif_dto_neant,qualite_declarant,qualite_declarant_for_p_d_f,qualite_mandat_cod_categorie_mandat,qualite_mandat_cod_type_mandat_fichier,qualite_mandat_code_liste_organe,qualite_mandat_label_organe,qualite_mandat_label_type_mandat,qualite_mandat_nom_categorie_mandat,qualite_mandat_type_mandat,regime_matrimonial,regime_matrimonial_comments,revenu_mandat_dto_neant,sci_dto_neant,type_declaration_id,type_declaration_label,uuid,valeurs_en_bourse_dto_neant,valeurs_non_en_bourse_dto_neant,vehicule_dto_neant
0,000765d9-da68-48c6-a95d-f34a12cacb5f,false,true,false,true,NaN,NaN,NaN,NaN,NaN,true,NaN,15/03/2020,08/02/2021 19:58:13,29/07/1951,DELAPORTE,Olivier,false,20171221,NaN,true,NaN,NaN,false,Elu local ou membre d’un établissement public ...,...,NaN,NaN,ADEL,true,true,NaN,NaN,Membre d’EPCI/Versailles grand parc,LOC,epci,NaN,EPCI,Membre d’EPCI,Elu local ou membre d’EPCI,Membre d’EPCI,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts,000765d9-da68-48c6-a95d-f34a12cacb5f,NaN,NaN,NaN
1,00138e83-44ec-4da1-89f3-37d2309a62a2,false,true,false,false,NaN,NaN,NaN,NaN,NaN,true,NaN,28/06/2020,17/08/2020 19:27:35,04/04/1964,SCHMITT,SYLVIE,NaN,20171221,NaN,true,NaN,NaN,true,Elu local ou membre d’un établissement public ...,...,Communes +20KH,NaN,ADEL,true,true,NaN,ADJOINT EDUCATION ENFANCE JEUNESSE,Maire ou adjoint municipal/Bordeaux (33)/ADJOI...,LOC,commune,COMM,Commune,Maire ou adjoint municipal,Elu local ou membre d’EPCI,Maire ou adjoint municipal,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts,00138e83-44ec-4da1-89f3-37d2309a62a2,NaN,NaN,NaN
2,0014115c-cbae-4bdd-98d1-39c8e6062095,false,true,false,false,NaN,NaN,NaN,NaN,NaN,true,NaN,01/07/2021,22/11/2021 16:19:31,26/06/1946,PELIEU,MICHEL,true,20171221,NaN,true,NaN,NaN,false,Membre ou dirigeant d’une autorité administrat...,...,NaN,NaN,ADEL,false,true,NaN,PRESIDENT DU CONSEIL GENERAL,PRESIDENT DU CONSEIL GENERAL,AAI,aai,AAI,AAI,NaN,Membre d’une AAI,Membre,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts modificative,0014115c-cbae-4bdd-98d1-39c8e6062095,NaN,NaN,NaN
3,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,false,true,true,false,NaN,NaN,NaN,NaN,NaN,true,NaN,28/09/2014,24/02/2021 10:25:03,14/03/1953,Gatel,Françoise,true,20171221,NaN,false,NaN,NaN,false,Député ou sénateur,...,Zones d'élection des parlementaires,NaN,ADEL,true,false,NaN,NaN,Sénateur/Ille-et-Vilaine(35),PAR,senateur,ZEP,Département d'élection,Sénateur,Député ou sénateur,Sénateur,NaN,NaN,NaN,NaN,DIA,Déclaration d'intérêts et d'activités modifica...,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,NaN,NaN,NaN
4,00243ad5-2191-4efc-884b-df9213413b17,false,true,false,true,NaN,NaN,NaN,NaN,NaN,true,NaN,26/06/2021,01/09/2021 10:38:28,30/11/1963,lecordier,nathalie,true,20171221,NaN,false,NaN,NaN,false,Elu local ou membre d’un établissement public ...,...,Départements,28,ADEL,false,true,NaN,NaN,Elu départemental/Seine-Maritime (76),LOC,departement,DEP,Département,Elu départemental,Elu local ou membre d’EPCI,Elu départemental,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts modificative,00243ad5-2191-4efc-884b-df9213413b17,NaN,NaN,NaN

In [48]:
# creation de la clé étrangère id_individu
declarations['id_individu'] = (declarations['declarant_nom']+declarations['declarant_prenom']+
                               declarations['declarant_date_naissance'])

In [49]:
# suppression des colonnes liées à la personne
declarations = declarations.drop(columns=['declarant_nom', 'declarant_prenom', 'declarant_date_naissance'])

In [50]:
# encodage id_declaration pour avoir un id en auto increment
encoder_id_declaration = LabelEncoder()
declarations['id_declaration'] = encoder_id_declaration.fit_transform(declarations['id_declaration'])

In [51]:
declarations.head()

chemins,id_declaration,activ_collaborateurs_dto_neant,activ_consultant_dto_neant,activ_prof_cinq_derniere_dto_neant,activ_prof_conjoint_dto_neant,assurance_vie_dto_neant,autre_bien_dto_neant,bien_diver_dto_neant,bien_etranger_dto_neant,chiffre_affaire,complete,comptes_bancaire_dto_neant,date_debut_mandat,date_depot,declaration_modificative,declaration_version,evenement_majeur_dto_neant,fonction_benevole_dto_neant,fond_dto_neant,immeuble_dto_neant,mandat_electif_dto_neant,mandat_label,nom_societe,nom_societe_mere,observation_interet_dto_neant,...,organe_organe_parent,origine,participation_dirigeant_dto_neant,participation_financiere_dto_neant,passif_dto_neant,qualite_declarant,qualite_declarant_for_p_d_f,qualite_mandat_cod_categorie_mandat,qualite_mandat_cod_type_mandat_fichier,qualite_mandat_code_liste_organe,qualite_mandat_label_organe,qualite_mandat_label_type_mandat,qualite_mandat_nom_categorie_mandat,qualite_mandat_type_mandat,regime_matrimonial,regime_matrimonial_comments,revenu_mandat_dto_neant,sci_dto_neant,type_declaration_id,type_declaration_label,uuid,valeurs_en_bourse_dto_neant,valeurs_non_en_bourse_dto_neant,vehicule_dto_neant,id_individu
0,0,false,true,false,true,NaN,NaN,NaN,NaN,NaN,true,NaN,15/03/2020,08/02/2021 19:58:13,false,20171221,NaN,true,NaN,NaN,false,Elu local ou membre d’un établissement public ...,NaN,NaN,true,...,NaN,ADEL,true,true,NaN,NaN,Membre d’EPCI/Versailles grand parc,LOC,epci,NaN,EPCI,Membre d’EPCI,Elu local ou membre d’EPCI,Membre d’EPCI,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts,000765d9-da68-48c6-a95d-f34a12cacb5f,NaN,NaN,NaN,DELAPORTEOlivier29/07/1951
1,1,false,true,false,false,NaN,NaN,NaN,NaN,NaN,true,NaN,28/06/2020,17/08/2020 19:27:35,NaN,20171221,NaN,true,NaN,NaN,true,Elu local ou membre d’un établissement public ...,NaN,NaN,true,...,NaN,ADEL,true,true,NaN,ADJOINT EDUCATION ENFANCE JEUNESSE,Maire ou adjoint municipal/Bordeaux (33)/ADJOI...,LOC,commune,COMM,Commune,Maire ou adjoint municipal,Elu local ou membre d’EPCI,Maire ou adjoint municipal,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts,00138e83-44ec-4da1-89f3-37d2309a62a2,NaN,NaN,NaN,SCHMITTSYLVIE04/04/1964
2,2,false,true,false,false,NaN,NaN,NaN,NaN,NaN,true,NaN,01/07/2021,22/11/2021 16:19:31,true,20171221,NaN,true,NaN,NaN,false,Membre ou dirigeant d’une autorité administrat...,NaN,NaN,false,...,NaN,ADEL,false,true,NaN,PRESIDENT DU CONSEIL GENERAL,PRESIDENT DU CONSEIL GENERAL,AAI,aai,AAI,AAI,NaN,Membre d’une AAI,Membre,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts modificative,0014115c-cbae-4bdd-98d1-39c8e6062095,NaN,NaN,NaN,PELIEUMICHEL26/06/1946
3,3,false,true,true,false,NaN,NaN,NaN,NaN,NaN,true,NaN,28/09/2014,24/02/2021 10:25:03,true,20171221,NaN,false,NaN,NaN,false,Député ou sénateur,NaN,NaN,false,...,NaN,ADEL,true,false,NaN,NaN,Sénateur/Ille-et-Vilaine(35),PAR,senateur,ZEP,Département d'élection,Sénateur,Député ou sénateur,Sénateur,NaN,NaN,NaN,NaN,DIA,Déclaration d'intérêts et d'activités modifica...,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,NaN,NaN,NaN,GatelFrançoise14/03/1953
4,4,false,true,false,true,NaN,NaN,NaN,NaN,NaN,true,NaN,26/06/2021,01/09/2021 10:38:28,true,20171221,NaN,false,NaN,NaN,false,Elu local ou membre d’un établissement public ...,NaN,NaN,true,...,28,ADEL,false,true,NaN,NaN,Elu départemental/Seine-Maritime (76),LOC,departement,DEP,Département,Elu départemental,Elu local ou membre d’EPCI,Elu départemental,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts modificative,00243ad5-2191-4efc-884b-df9213413b17,NaN,NaN,NaN,lecordiernathalie30/11/1963

In [52]:
# encodage id_individus
declarations['id_individu'] = encoder_id_individu.transform(declarations['id_individu'])

In [53]:
declarations.head()

chemins,id_declaration,activ_collaborateurs_dto_neant,activ_consultant_dto_neant,activ_prof_cinq_derniere_dto_neant,activ_prof_conjoint_dto_neant,assurance_vie_dto_neant,autre_bien_dto_neant,bien_diver_dto_neant,bien_etranger_dto_neant,chiffre_affaire,complete,comptes_bancaire_dto_neant,date_debut_mandat,date_depot,declaration_modificative,declaration_version,evenement_majeur_dto_neant,fonction_benevole_dto_neant,fond_dto_neant,immeuble_dto_neant,mandat_electif_dto_neant,mandat_label,nom_societe,nom_societe_mere,observation_interet_dto_neant,...,organe_organe_parent,origine,participation_dirigeant_dto_neant,participation_financiere_dto_neant,passif_dto_neant,qualite_declarant,qualite_declarant_for_p_d_f,qualite_mandat_cod_categorie_mandat,qualite_mandat_cod_type_mandat_fichier,qualite_mandat_code_liste_organe,qualite_mandat_label_organe,qualite_mandat_label_type_mandat,qualite_mandat_nom_categorie_mandat,qualite_mandat_type_mandat,regime_matrimonial,regime_matrimonial_comments,revenu_mandat_dto_neant,sci_dto_neant,type_declaration_id,type_declaration_label,uuid,valeurs_en_bourse_dto_neant,valeurs_non_en_bourse_dto_neant,vehicule_dto_neant,id_individu
0,0,false,true,false,true,NaN,NaN,NaN,NaN,NaN,true,NaN,15/03/2020,08/02/2021 19:58:13,false,20171221,NaN,true,NaN,NaN,false,Elu local ou membre d’un établissement public ...,NaN,NaN,true,...,NaN,ADEL,true,true,NaN,NaN,Membre d’EPCI/Versailles grand parc,LOC,epci,NaN,EPCI,Membre d’EPCI,Elu local ou membre d’EPCI,Membre d’EPCI,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts,000765d9-da68-48c6-a95d-f34a12cacb5f,NaN,NaN,NaN,1432
1,1,false,true,false,false,NaN,NaN,NaN,NaN,NaN,true,NaN,28/06/2020,17/08/2020 19:27:35,NaN,20171221,NaN,true,NaN,NaN,true,Elu local ou membre d’un établissement public ...,NaN,NaN,true,...,NaN,ADEL,true,true,NaN,ADJOINT EDUCATION ENFANCE JEUNESSE,Maire ou adjoint municipal/Bordeaux (33)/ADJOI...,LOC,commune,COMM,Commune,Maire ou adjoint municipal,Elu local ou membre d’EPCI,Maire ou adjoint municipal,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts,00138e83-44ec-4da1-89f3-37d2309a62a2,NaN,NaN,NaN,4608
2,2,false,true,false,false,NaN,NaN,NaN,NaN,NaN,true,NaN,01/07/2021,22/11/2021 16:19:31,true,20171221,NaN,true,NaN,NaN,false,Membre ou dirigeant d’une autorité administrat...,NaN,NaN,false,...,NaN,ADEL,false,true,NaN,PRESIDENT DU CONSEIL GENERAL,PRESIDENT DU CONSEIL GENERAL,AAI,aai,AAI,AAI,NaN,Membre d’une AAI,Membre,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts modificative,0014115c-cbae-4bdd-98d1-39c8e6062095,NaN,NaN,NaN,3921
3,3,false,true,true,false,NaN,NaN,NaN,NaN,NaN,true,NaN,28/09/2014,24/02/2021 10:25:03,true,20171221,NaN,false,NaN,NaN,false,Député ou sénateur,NaN,NaN,false,...,NaN,ADEL,true,false,NaN,NaN,Sénateur/Ille-et-Vilaine(35),PAR,senateur,ZEP,Département d'élection,Sénateur,Député ou sénateur,Sénateur,NaN,NaN,NaN,NaN,DIA,Déclaration d'intérêts et d'activités modifica...,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,NaN,NaN,NaN,2308
4,4,false,true,false,true,NaN,NaN,NaN,NaN,NaN,true,NaN,26/06/2021,01/09/2021 10:38:28,true,20171221,NaN,false,NaN,NaN,false,Elu local ou membre d’un établissement public ...,NaN,NaN,true,...,28,ADEL,false,true,NaN,NaN,Elu départemental/Seine-Maritime (76),LOC,departement,DEP,Département,Elu départemental,Elu local ou membre d’EPCI,Elu départemental,NaN,NaN,NaN,NaN,DI,Déclaration d'intérêts modificative,00243ad5-2191-4efc-884b-df9213413b17,NaN,NaN,NaN,5611

In [54]:
# export en csv
declarations.to_csv(folder_export + 'declarations.csv', index=False)

## Table attached_files
lié à la table declarations

In [29]:
def id_table(nom_table, champs_levier):

    # ajout de l'id de la table
    ids_table = []
    champs_table = []

    # creation de l'id de la table, qui s'incrémente à chaque nouvel élément, c'est à dire à chaque 'champs_repere_nouvelle_ligne'
    for element in tqdm(nom_table['champs'].values):
        champs_table.append(element)
        i = champs_table.count(champs_levier) - 1
        ids_table.append(i)

    nom_table['id_table'] = ids_table

    return nom_table

In [56]:
data3['chemins'][data3['chemins'].str.contains('attachedFiles')].unique()

array(['attachedFiles/attachedFiles/fileName',
       'attachedFiles/attachedFiles/serverFileName'], dtype=object)

In [57]:
# chemins des champs de la table
attached_files = data3[data3['chemins'].str.contains('attachedFiles')][['id_declaration',
                                                                        'champs', 'valeurs']].reset_index(drop=True)
attached_files.head(100)

,id_declaration,champs,valeurs
0,4344aaa1-874d-4e6d-9b1a-45f7725b710c,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
1,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
2,21916899-a643-428c-824e-3aedf9ee103e,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
3,c40ab214-b21e-43b6-95a2-36d5860dc526,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
4,ac693815-1521-4a79-a314-6bd830de8988,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
5,61853e75-80cc-457b-865c-80456d4a0985,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
6,a2893249-f253-4cb4-bb9d-f7fcec066d31,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
7,2b6da666-15d3-4864-9231-7a7dd5ae9dda,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
8,d18ae83a-4925-4b45-ba5d-3ee5b9090fc3,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
9,71a9d498-0801-40f2-bab2-b44126698b19,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
10,3e209d45-8656-45ac-a8c8-451542abe786,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
11,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
12,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
13,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
14,76933453-9495-40e7-8c1a-e5676dd82004,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
15,b0268727-af55-4a2a-98fb-6bf6b88cd82b,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
16,7506f05d-a603-4a90-8bcb-4e2aab1dea4c,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
17,6d926a52-18e5-45bd-b9d0-682cfb19325d,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
18,ce0e903b-2a40-4009-9a63-348b71bc3078,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
19,a08caa34-fbe2-4cc9-a07e-d7c6e0149b3f,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
20,4e8433cd-e3c1-4930-91e9-b7e53303a7aa,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
21,38549f62-414c-4a76-9c29-bc402a82aa41,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
22,132aebbd-17cf-43bb-9cdb-aeac43c2d634,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
23,7a06d4e4-ee72-48ea-95da-275846da3e89,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
24,8f48a970-d4cb-4886-b087-dd22a8b74d50,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
25,2075e1cf-fb7a-4142-9223-9e47ecb4de1b,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
26,ee0ade64-f77f-4ba4-ad90-8c1e243392ce,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
27,1e08af8a-865d-40c3-9c93-7872153e2857,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
28,46898dd0-2753-4a49-9202-f3c9c3ee1380,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
29,ca9fc0a4-be03-43db-acf2-7f011b8fe34d,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
30,01771bd8-9f1a-4e3b-9897-617cd0dea0c9,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
31,90a3cde6-02a2-4a52-a754-7d8a45f8632d,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
32,40bc37b0-7161-4e04-89ec-967146404c86,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
33,4cdd6e24-0515-4250-b13a-b9b65242cf7f,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
34,c5a321ef-d986-426a-939d-e01bd2358fc0,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
35,6f60e21b-9ca0-4b09-b25c-b6be6dd54b9f,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
36,1ab58bff-da43-4495-959e-2f9e81668da2,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
37,95657c04-d22b-4d3a-aa7d-9144261f339b,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
38,18513c94-5980-4e77-b496-56f6ba350f02,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
39,8fb932d5-2a0d-4962-ae7a-e633dac8b3f5,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
40,948cfdd1-66bb-4484-a8b6-b42017c59140,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
41,4a50a546-6bfb-4144-bffe-51c44ec5ed08,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
42,b9a295db-3616-4938-80c8-853bd00327ef,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
43,612af3ef-76a1-4b74-88f6-352da2b49dc9,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
44,fd9c9386-c2a0-4b7e-8311-0958c721f59c,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
45,c3d6e8d4-2c68-4669-b2f5-16a3ba0a4fc0,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
46,d94670d9-8b50-409a-8c66-2217499145bf,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
47,bdcb5b0b-ea72-4f5e-91f2-4dfd1308a8bd,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
48,daccb11b-67a9-4006-bcc8-ef7b3b6baed0,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
49,f0a33072-6fea-4cd9-ae33-5b9371b1e59b,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
50,caba60fd-79b9-426c-9fca-5e3c187fbdc4,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
51,d71c49e0-64a4-4210-9611-f44659e29802,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
52,6824b541-2df6-45e8-9a6e-80942d186471,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
53,514843e4-3dbc-468c-ad86-2093785c64ee,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
54,f6ceafe7-5a92-4f2d-a9d8-566989f7a9ee,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
55,8ea9de29-ff8d-4847-b455-89bfe264c8fc,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
56,909301a8-5fcb-44d6-8b32-a21806d88dd1,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
57,65d84ebb-546e-4a03-b5fe-ca5be52520c3,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
58,9f007b4d-7b8a-4dc6-891e-2e4d2a07f980,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
59,c19ed3bd-9145-4ac9-895e-648f08b5146c,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
60,3692fd40-8ef4-478f-be3e-5b169b063200,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
61,f9c892a0-f124-4f1d-a8e7-32ba6a998516,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
62,29e717fa-e4a5-49cd-b043-dad5f4f975c3,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
63,5c701184-cffd-44bf-8c20-3493e4863bd7,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
64,5c701184-cffd-44bf-8c20-3493e4863bd7,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
65,6645675d-9453-4a5f-a182-b9e39f97c3e5,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
66,e6d7f65d-f1a0-47c3-b659-49808c3fa5c3,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
67,a90ca672-2b3a-4836-b735-0581938f1513,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
68,3f067d1b-acae-4898-b924-79e426ad4bf0,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
69,23f1de0b-a375-40bd-9b45-e07f65014226,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
70,3151507c-0e59-43b5-98bc-65275c1cb6ac,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
71,32af39d3-56e4-4b22-be79-c74d6e9561bf,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
72,a48634ae-b71c-4fbf-9827-af04e2cb798d,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
73,b7676032-621b-42bb-a7ed-24893134ec6e,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
74,f478fa4b-f95b-4338-8dd3-b92fd5dc52d6,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
75,f8a279bd-84fb-4ba4-9714-f94b57562cd2,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
76,926c95ed-6e85-4d3d-b6b8-19e870d1bea7,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
77,7c322b98-e890-42c8-9b48-d86513fe892b,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
78,c9cf3691-13b9-4a7d-9812-d8c185063bc9,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
79,99b46254-7049-4ed7-8576-c58a1654bac1,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
80,6a52bcca-8741-4382-b417-83d842624b63,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
81,19b2805b-9454-48b2-96ff-b6eb9c524893,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
82,4794faad-da62-40f8-a76d-8e05539adeb8,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
83,62db8518-aed9-46d9-a6bd-118951830c27,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
84,9fff6d0c-a4ca-4e99-becd-017e413f2db9,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
85,a976a177-5b44-456c-9567-215e80d50ae4,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
86,b4ce8798-a171-465e-9749-78b9ea728136,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
87,1bf15c54-2187-4fe9-a6da-d56d7e9d7fff,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
88,d8e35fc2-5f6a-460a-8d2b-ef905c53cdb7,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
89,3423f304-57a9-4019-bc7e-812e20026af1,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
90,24026c0d-4a01-4167-bc1d-728d3f36df2c,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
91,4ecdc53d-7fff-41cd-a1a3-fcf76af721c0,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
92,f9c3f375-fe2f-4d8b-adec-ddebe1d0e198,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
93,5aca390d-5eb7-4b05-842d-cbaf5c4a5259,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
94,4b886c35-09df-42a9-bf16-4d779a3cb3df,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
95,4cef2f52-5eec-4eda-91d5-14633d39a06b,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
96,29354efc-115c-4505-930a-8e4f4d620f85,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
97,86dd9c5d-41ec-44aa-b664-f8d8ba099348,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
98,c4221cda-18e7-4ee2-96a5-2bbfa7b584e9,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
99,7789d319-d572-43cd-8534-20568f036525,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML

In [58]:
# creation de l'id de la table
attached_files = attached_files.reset_index()

# renommage de l'id pour la table
attached_files = attached_files.rename(columns={'index':'id_file'})

In [59]:
# encodage id_declaration
attached_files['id_declaration'] = encoder_id_declaration.transform(attached_files['id_declaration'])

In [60]:
# pivot des champs de la table
attached_files = attached_files.pivot(index=['id_file', 'id_declaration'], columns='champs',
                                      values='valeurs').reset_index()

In [61]:
# export en csv
attached_files.to_csv(folder_export + 'attached_files.csv', index=False)

## Table activProfConjointDto
Table métier du conjoint

In [62]:
# conditions de mapping entre le chemin xml et les champs de la table en cours
mask_activProfConjointDto = (data3['chemins'].str.contains('activProfConjointDto/items/', na=False))

champs_activProfConjointDto = data3[mask_activProfConjointDto]['chemins'].unique()
champs_activProfConjointDto

array(['activProfConjointDto/items/items/motif/id',
       'activProfConjointDto/items/items/nomConjoint',
       'activProfConjointDto/items/items/employeurConjoint',
       'activProfConjointDto/items/items/activiteProf',
       'activProfConjointDto/items/items/commentaire',
       'activProfConjointDto/items/items/motif/label'], dtype=object)

In [63]:
# table activProfConjointDto
activProfConjointDto = data3[data3['chemins'].isin(champs_activProfConjointDto)][['id_declaration', 'champs', 'valeurs']]
activProfConjointDto.head()

,id_declaration,champs,valeurs
16,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
17,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomConjoint,[Données non publiées]
18,4344aaa1-874d-4e6d-9b1a-45f7725b710c,employeurConjoint,CENTRE HOSPITALIER DU HAUT-BUGEY
19,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activiteProf,Infirmière
395,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,id,CREATION

In [64]:
# creation de l'id
activProfConjointDto = id_table(nom_table=activProfConjointDto, champs_levier='id')
activProfConjointDto.head(100)

100%|██████████████████████████████████████████████████████████████████████████| 33684/33684 [00:07<00:00, 4317.42it/s]

,id_declaration,champs,valeurs,id_table
16,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,0
17,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomConjoint,[Données non publiées],0
18,4344aaa1-874d-4e6d-9b1a-45f7725b710c,employeurConjoint,CENTRE HOSPITALIER DU HAUT-BUGEY,0
19,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activiteProf,Infirmière,0
395,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,id,CREATION,1
396,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,nomConjoint,[Données non publiées],1
397,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,employeurConjoint,CENTRE HOSPITALIER DU HAUT-BUGEY,1
398,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,activiteProf,Infirmière,1
816,21916899-a643-428c-824e-3aedf9ee103e,id,CREATION,2
817,21916899-a643-428c-824e-3aedf9ee103e,nomConjoint,[Données non publiées],2
818,21916899-a643-428c-824e-3aedf9ee103e,employeurConjoint,ODIGO,2
819,21916899-a643-428c-824e-3aedf9ee103e,activiteProf,DIRECTEUR DE PROJET CADRE,2
1019,c40ab214-b21e-43b6-95a2-36d5860dc526,id,CREATION,3
1020,c40ab214-b21e-43b6-95a2-36d5860dc526,nomConjoint,[Données non publiées],3
1021,c40ab214-b21e-43b6-95a2-36d5860dc526,employeurConjoint,ODIGO,3
1022,c40ab214-b21e-43b6-95a2-36d5860dc526,activiteProf,DIRECTEUR DE PROJET CADRE,3
1223,ac693815-1521-4a79-a314-6bd830de8988,id,CREATION,4
1224,ac693815-1521-4a79-a314-6bd830de8988,commentaire,[Données non publiées],4
1225,ac693815-1521-4a79-a314-6bd830de8988,nomConjoint,[Données non publiées],4
1226,ac693815-1521-4a79-a314-6bd830de8988,employeurConjoint,Néant,4
1227,ac693815-1521-4a79-a314-6bd830de8988,activiteProf,Néant,4
1356,61853e75-80cc-457b-865c-80456d4a0985,id,CREATION,5
1357,61853e75-80cc-457b-865c-80456d4a0985,nomConjoint,[Données non publiées],5
1358,61853e75-80cc-457b-865c-80456d4a0985,employeurConjoint,neant,5
1359,61853e75-80cc-457b-865c-80456d4a0985,activiteProf,néant retraité,5
2387,3e209d45-8656-45ac-a8c8-451542abe786,id,CREATION,6
2388,3e209d45-8656-45ac-a8c8-451542abe786,commentaire,[Données non publiées],6
2389,3e209d45-8656-45ac-a8c8-451542abe786,nomConjoint,[Données non publiées],6
2390,3e209d45-8656-45ac-a8c8-451542abe786,employeurConjoint,SDIS [Données non publiées],6
2391,3e209d45-8656-45ac-a8c8-451542abe786,activiteProf,pompier professionnel,6
2673,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,id,CREATION,7
2674,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,commentaire,en retraite [Données non publiées],7
2675,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,nomConjoint,[Données non publiées],7
2676,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,employeurConjoint,[Données non publiées],7
2677,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,activiteProf,psychiatre attachée en tabacologie et expert d...,7
2991,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,id,CREATION,8
2992,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,commentaire,en retraite [Données non publiées],8
2993,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,nomConjoint,[Données non publiées],8
2994,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,employeurConjoint,[Données non publiées],8
2995,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,activiteProf,psychiatre attachée en tabacologie et expert d...,8
3341,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,id,CREATION,9
3342,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,commentaire,en retraite [Données non publiées],9
3343,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,nomConjoint,[Données non publiées],9
3344,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,employeurConjoint,[Données non publiées],9
3345,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,activiteProf,psychiatre attachée en tabacologie et expert d...,9
3618,76933453-9495-40e7-8c1a-e5676dd82004,id,CREATION,10
3619,76933453-9495-40e7-8c1a-e5676dd82004,nomConjoint,[Données non publiées],10
3620,76933453-9495-40e7-8c1a-e5676dd82004,employeurConjoint,ORANGE,10
3621,76933453-9495-40e7-8c1a-e5676dd82004,activiteProf,Employé de bureau,10
3754,b0268727-af55-4a2a-98fb-6bf6b88cd82b,id,CREATION,11
3755,b0268727-af55-4a2a-98fb-6bf6b88cd82b,nomConjoint,[Données non publiées],11
3756,b0268727-af55-4a2a-98fb-6bf6b88cd82b,employeurConjoint,ORANGE,11
3757,b0268727-af55-4a2a-98fb-6bf6b88cd82b,activiteProf,Employé de bureau,11
4009,7506f05d-a603-4a90-8bcb-4e2aab1dea4c,id,CREATION,12
4010,7506f05d-a603-4a90-8bcb-4e2aab1dea4c,nomConjoint,[Données non publiées],12
4011,7506f05d-a603-4a90-8bcb-4e2aab1dea4c,employeurConjoint,RODEZ AGGLOMERATION,12
4012,7506f05d-a603-4a90-8bcb-4e2aab1dea4c,activiteProf,Rédacteur principal,12
4526,6d926a52-18e5-45bd-b9d0-682cfb19325d,id,CREATION,13
4527,6d926a52-18e5-45bd-b9d0-682cfb19325d,nomConjoint,[Données non publiées],13
4528,6d926a52-18e5-45bd-b9d0-682cfb19325d,employeurConjoint,RODEZ AGGLOMERATION,13
4529,6d926a52-18e5-45bd-b9d0-682cfb19325d,activiteProf,Rédacteur principal,13
7903,132aebbd-17cf-43bb-9cdb-aeac43c2d634,id,CREATION,14
7904,132aebbd-17cf-43bb-9cdb-aeac43c2d634,nomConjoint,[Données non publiées],14
7905,132aebbd-17cf-43bb-9cdb-aeac43c2d634,employeurConjoint,sans,14
7906,132aebbd-17cf-43bb-9cdb-aeac43c2d634,activiteProf,neant,14
7998,7a06d4e4-ee72-48ea-95da-275846da3e89,id,CREATION,15
7999,7a06d4e4-ee72-48ea-95da-275846da3e89,nomConjoint,[Données non publiées],15
8000,7a06d4e4-ee72-48ea-95da-275846da3e89,employeurConjoint,[Données non publiées],15
8001,7a06d4e4-ee72-48ea-95da-275846da3e89,activiteProf,néant,15
8130,8f48a970-d4cb-4886-b087-dd22a8b74d50,id,CREATION,16
8131,8f48a970-d4cb-4886-b087-dd22a8b74d50,nomConjoint,[Données non publiées],16
8132,8f48a970-d4cb-4886-b087-dd22a8b74d50,employeurConjoint,EBEN,16
8133,8f48a970-d4cb-4886-b087-dd22a8b74d50,activiteProf,[Données non publiées],16
8239,2075e1cf-fb7a-4142-9223-9e47ecb4de1b,id,CREATION,17
8240,2075e1cf-fb7a-4142-9223-9e47ecb4de1b,nomConjoint,[Données non publiées],17
8241,2075e1cf-fb7a-4142-9223-9e47ecb4de1b,employeurConjoint,EBEN,17
8242,2075e1cf-fb7a-4142-9223-9e47ecb4de1b,activiteProf,[Données non publiées],17
8496,ee0ade64-f77f-4ba4-ad90-8c1e243392ce,id,CREATION,18
8497,ee0ade64-f77f-4ba4-ad90-8c1e243392ce,nomConjoint,[Données non publiées],18
8498,ee0ade64-f77f-4ba4-ad90-8c1e243392ce,employeurConjoint,EBEN,18
8499,ee0ade64-f77f-4ba4-ad90-8c1e243392ce,activiteProf,[Données non publiées],18
8755,46898dd0-2753-4a49-9202-f3c9c3ee1380,id,CREATION,19
8756,46898dd0-2753-4a49-9202-f3c9c3ee1380,commentaire,[Données non publiées],19
8757,46898dd0-2753-4a49-9202-f3c9c3ee1380,nomConjoint,[Données non publiées],19
8758,46898dd0-2753-4a49-9202-f3c9c3ee1380,employeurConjoint,VUITTON,19
8759,46898dd0-2753-4a49-9202-f3c9c3ee1380,activiteProf,[Données non publiées],19
8906,ca9fc0a4-be03-43db-acf2-7f011b8fe34d,id,CREATION,20
8907,ca9fc0a4-be03-43db-acf2-7f011b8fe34d,nomConjoint,[Données non publiées],20
8908,ca9fc0a4-be03-43db-acf2-7f011b8fe34d,employeurConjoint,CHU Nantes,20
8909,ca9fc0a4-be03-43db-acf2-7f011b8fe34d,activiteProf,"Ingenieur Hospitalier, [Données non pu...",20
9062,01771bd8-9f1a-4e3b-9897-617cd0dea0c9,id,CREATION,21
9063,01771bd8-9f1a-4e3b-9897-617cd0dea0c9,nomConjoint,[Données non publiées],21
9064,01771bd8-9f1a-4e3b-9897-617cd0dea0c9,employeurConjoint,[Données non publiées],21
9065,01771bd8-9f1a-4e3b-9897-617cd0dea0c9,activiteProf,Professeur des écoles,21
10233,4cdd6e24-0515-4250-b13a-b9b65242cf7f,id,CREATION,22
10234,4cdd6e24-0515-4250-b13a-b9b65242cf7f,nomConjoint,[Données non publiées],22
10235,4cdd6e24-0515-4250-b13a-b9b65242cf7f,employeurConjoint,Retraitée,22
10236,4cdd6e24-0515-4250-b13a-b9b65242cf7f,activiteProf,Néant,22
12141,4a50a546-6bfb-4144-bffe-51c44ec5ed08,id,CREATION,23
12142,4a50a546-6bfb-4144-bffe-51c44ec5ed08,nomConjoint,[Données non publiées],23

In [65]:
# creation de l'index pour le pivot
activProfConjointDto = activProfConjointDto.reset_index(drop=True).rename(columns={'id_table':'id_activProfConjointDto'})

In [66]:
# encodage id_declaration
activProfConjointDto['id_declaration'] = encoder_id_declaration.transform(activProfConjointDto['id_declaration'])
activProfConjointDto.head()

,id_declaration,champs,valeurs,id_activProfConjointDto
0,2914,id,CREATION,0
1,2914,nomConjoint,[Données non publiées],0
2,2914,employeurConjoint,CENTRE HOSPITALIER DU HAUT-BUGEY,0
3,2914,activiteProf,Infirmière,0
4,10647,id,CREATION,1

In [67]:
# supression des doublons
activProfConjointDto = activProfConjointDto.drop(activProfConjointDto[activProfConjointDto.duplicated(subset=['id_declaration','champs', 'id_activProfConjointDto'],
                                                                                                      keep='last')].index)

In [68]:
activProfConjointDto = activProfConjointDto.pivot(index=['id_declaration', 'id_activProfConjointDto'], columns='champs',
                                                  values='valeurs').reset_index()

In [69]:
activProfConjointDto.head(100)

champs,id_declaration,id_activProfConjointDto,activiteProf,commentaire,employeurConjoint,id,label,nomConjoint
0,1,7001,[Données non publiées],NaN,dekra,CREATION,NaN,[Données non publiées]
1,2,5982,[Données non publiées],[Données non publiées],SAS SLTS,CREATION,NaN,[Données non publiées]
2,3,3122,Retraité,NaN,Retraité,CREATION,NaN,[Données non publiées]
3,5,2000,Chargé de mission,NaN,Région Nouvelle-Aquitaine,CREATION,NaN,[Données non publiées]
4,6,4433,retraitée,[Données non publiées],NEANT,CREATION,NaN,[Données non publiées]
5,8,1144,[Données non publiées] agent immobilier ...,NaN,Arlim Prestige,CREATION,NaN,[Données non publiées]
6,9,5019,Direction Artistique & Graphisme,NaN,Entreprise Individuelle,CREATION,NaN,[Données non publiées]
7,9,5020,Conception et commercialisation de vêtements M...,Création en 2018. Pas encore de revenus généré...,[Données non publiées] SAS,CREATION,NaN,[Données non publiées]
8,10,4289,néant,Arrêt d'activité le 31/12/2013,néant,CREATION,NaN,[Données non publiées]
9,12,5820,Chargé de recherche puis directrice de recherche,"A` titre ponctuel, elle peut apporter son expe...",CNRS,CREATION,NaN,[Données non publiées]
10,13,5500,[Données non publiées],NaN,PCM TEARI,CREATION,NaN,[Données non publiées]
11,14,3490,Médecin généraliste,NaN,Profession libérale,CREATION,NaN,[Données non publiées]
12,15,3330,Secrétaire [Données non publiées],NaN,Commune de Lormont,CREATION,NaN,[Données non publiées]
13,18,6114,[Données non publiées],NaN,CEA,CREATION,NaN,[Données non publiées]
14,19,3005,[Données non publiées],activité de crèche parentale associative,Association [Données non publiées],CREATION,NaN,[Données non publiées]
15,20,6547,[Données non publiées],NaN,université [Données non publiées],CREATION,NaN,[Données non publiées]
16,21,245,Maitre de conférences,NaN,Université [Données non publiées],CREATION,NaN,[Données non publiées]
17,23,537,Directeur général,NaN,[Données non publiées],CREATION,NaN,[Données non publiées]
18,24,2603,VENDEUSE MAGASIN BOULANGERIE PATISSERIE,NaN,BOULANGERIE PATISSERIE [Données non pub...,CREATION,NaN,[Données non publiées]
19,26,3197,Founder and Managing Director,NaN,Livemore Pte Ltd,CREATION,NaN,[Données non publiées]
20,27,4186,Kinésithérapeute,[Données non publiées],profession libérale,CREATION,NaN,[Données non publiées]
21,28,1520,[Données non publiées],[Données non publiées],Région Grand Est,CREATION,NaN,[Données non publiées]
22,30,5511,Avocate,NaN,Néant,CREATION,NaN,[Données non publiées]
23,31,2347,Formateur / enseignement agricole privé sous c...,NaN,Maison Familiale et Rurale [Données non...,CREATION,NaN,[Données non publiées]
24,32,938,Ergonome/Psychologue du travail [Donnée...,NaN,[Données non publiées],CREATION,NaN,[Données non publiées]
25,33,4031,[Données non publiées],[Données non publiées],conseil départemental de La Réunion,CREATION,NaN,[Données non publiées]
26,34,6851,[Données non publiées],NaN,PRATICIEN HOSPITALIER,CREATION,NaN,[Données non publiées]
27,35,759,[Données non publiées],NaN,SOFIPEL,CREATION,NaN,[Données non publiées]
28,36,1607,Retraitée de l'Education Nationale,NaN,Néant,CREATION,NaN,[Données non publiées]
29,37,4429,Infirmière Puéricultrice [Données non ...,Retraitée [Données non publiées],C C A S [Données non publiées],CREATION,NaN,[Données non publiées]
30,38,817,"expert-comptable, associé et co-gérant de la s...",[Données non publiées],[Données non publiées],CREATION,NaN,[Données non publiées]
31,40,1133,chargée de communication,NaN,Sarl Bihannic,CREATION,NaN,[Données non publiées]
32,44,5790,Comptable,NaN,[Données non publiées],CREATION,NaN,[Données non publiées]
33,46,4981,Assistante de Direction,NaN,Fédération Française du Bâtiment,CREATION,NaN,[Données non publiées]
34,47,2055,Etudiante,NaN,Néant,CREATION,NaN,[Données non publiées]
35,48,6540,Déléguée [Données non publiées],[Données non publiées],UDAF [Données non publiées],CREATION,NaN,[Données non publiées]
36,50,1296,[Données non publiées],[Données non publiées] retraite [Do...,Groupama Méditerranée,CREATION,NaN,[Données non publiées]
37,51,208,peinture,NaN,auto entrepreneur,CREATION,NaN,[Données non publiées]
38,52,550,Chef de Division et Secrétaire Exécutive de Mo...,[Données non publiées],Conseil de l'Europe,CREATION,NaN,[Données non publiées]
39,53,3937,[Données non publiées],NaN,BlueSolutions,CREATION,NaN,[Données non publiées]
40,54,1865,[Données non publiées],NaN,Ville de Paris,CREATION,NaN,[Données non publiées]
41,55,502,[Données non publiées],[Données non publiées],FlexThings,CREATION,NaN,[Données non publiées]
42,56,7328,Manager de transition,NaN,Mickael Page Interim,CREATION,NaN,[Données non publiées]
43,57,3669,ATTACHE TERRITORIALE,NaN,MAIRIE D'EPINAY SUR SEINE,CREATION,NaN,[Données non publiées]
44,58,6209,Aide Médico Psycologique en EHPAD [Don...,NaN,ASSOCIATION LE RULEAU,CREATION,NaN,[Données non publiées]
45,59,278,IDE,en retraite [Données non publiées],hopital [Données non publiées],CREATION,Nouvelle activité,[Données non publiées]
46,60,21,Professeur des écoles,NaN,[Données non publiées],CREATION,NaN,[Données non publiées]
47,62,591,Infirmière,NaN,Hopital [Données non publiées],CREATION,NaN,[Données non publiées]
48,64,3308,Téléconseillère,[Données non publiées],La Banque Postale,CREATION,NaN,[Données non publiées]
49,65,3679,attachée,NaN,Conseil Départemental de Mayottel,CREATION,NaN,[Données non publiées]
50,66,7069,Infimière,NaN,SFS,CREATION,NaN,[Données non publiées]
51,67,2407,entrepreneur de travaux agricoles,[Données non publiées],[Données non publiées],CREATION,NaN,[Données non publiées]
52,70,3401,Responsable d'équipe,NaN,ENEDIS,CREATION,NaN,[Données non publiées]
53,71,5212,Régisseur [Données non publiées],NaN,Mairie de Clermont-Ferrand,CREATION,NaN,[Données non publiées]
54,72,612,CADRE ADMINISTRATIF,NaN,STE MECAFORM,CREATION,NaN,[Données non publiées]
55,73,1171,INFIRMIERE LIBERALE,NaN,PROFESSION LIBERALE,CREATION,NaN,[Données non publiées]
56,74,6406,Pharmacienne Assistante,NaN,Pharmacie [Données non publiées],CREATION,NaN,[Données non publiées]
57,76,7088,AutoEntrepreneur [Données non publiées],NaN,Retraité du CEA,CREATION,NaN,[Données non publiées]
58,77,780,[Données non publiées],NaN,régie networks,CREATION,NaN,[Données non publiées]
59,79,3551,Néant,NaN,Neant,CREATION,NaN,[Données non publiées]
60,81,5010,Infirmière,NaN,[Données non publiées],CREATION,NaN,[Données non publiées]
61,83,4957,ENSEIGNANTE,NaN,EDUCATION NATIONALE,CREATION,NaN,[Données non publiées]
62,84,3765,Charge [Données non publiées],NaN,la Caisse d'allocations Familiales,CREATION,NaN,[Données non publiées]
63,86,81,directrice [Données non publiées],NaN,palais des congrès,CREATION,NaN,[Données non publiées]
64,89,572,Dirigeant,NaN,Tout en Vélo Grenoble,CREATION,NaN,[Données non publiées]
65,90,825,[Données non publiées] [Données non...,[Données non publiées],Hynamics,CREATION,NaN,[Données non publiées]
66,92,791,Néant,NaN,Néant,CREATION,NaN,[Données non publiées]
67,93,7440,Néant,NaN,Néant,CREATION,NaN,[Données non publiées]
68,95,1151,[Données non publiées],NaN,AUCUN,CREATION,NaN,[Données non publiées]
69,96,4036,"OFFICIER PILOTE, ARMÉE DE L'AIR",NaN,MINISTÈRE DE LA DÉFENSE - ARMÉE DE L'AIR,CREATION,NaN,[Données non publiées]
70,97,4634,Exploitant agricole,NaN,GAEC DE KERMORIN,CREATION,NaN,[Données non publiées]
71,98,4544,Infirmière libérale,NaN,Cabinet infirmier [Données non publiées],CREATION,NaN,[Données non publiées]
72,99,2340,COMPTABLE,NaN,[Données non publiées],CREATION,NaN,[Données non publiées]
73,101,1666,Député des Bouches-du-Rhône,NaN,[Données non publiées],CREATION,NaN,[Données non publiées]
74,104,2931,néant,retraite,retraite,CREATION,NaN,[Données non publiées]
75,107,7234,[Données non publiées],NaN,Ville de Paris,CREATION,NaN,[Données non publiées]
76,108,6526,Agent d’assurance [Données non publiées],NaN,Collecteam,CREATION,NaN,[Données non publiées]
77,109,6588,PROFESSEUR,NaN,EDUCATION NATIONALE,CREATION,NaN,[Données non publiées]
78,110,2148,retraité,NaN,0,CREATION,NaN,[Données non publiées]
79,111,4500,journaliste,NaN,Le Revenu,CREATION,NaN,[Données non publiées]
80,112,3561,sans,[Données non publiées],sans,CREATION,NaN,[Données non publiées]
81,113,4715,gérance,NaN,saint-crepin sarl,CREATION,NaN,[Données non publiées]
82,113,4716,co-gérance,NaN,crépin-petit sn,CREATION,NaN,[Données non publiées]
83,113,4717,co-gérance,NaN,mode harmony sn,CREATION,NaN,[Données non publiées]
84,113,4718,gérance,NaN,aura buttons,CREATION,NaN,[Données non publiées]
85,113,4719,gérance,NaN,wing motors sarl,CREATION,NaN,[Données non publiées]
86,113,4720,gérance,NaN,infopress sarl,CREATION,NaN,[Données non publiées]
87,114,7710,Retraitée,NaN,Retraitée,CREATION,NaN,[Données non publiées]
88,115,1300,agent qualité et formation,[Données non publiées],Booking.com,CREATION,NaN,[Données non publiées]
89,116,6948,Ingénieur,NaN,ENS [Données non publiées],CREATION,NaN,[Données non publiées]
90,117,3258,SARL Le Petit Quai [Données non publiée...,NaN,Co-Gérante SARL,CREATION,NaN,[Données non publiées]
91,118,4536,[Données non publiées],NaN,[Données non publiées],CREATION,NaN,[Données non publiées]
92,118,4537,[Données non publiées],NaN,Retraite,CREATION,NaN,[Données non publiées]
93,120,433,pharmacienne [Données non publiées],salariée,PHARMACIE,CREATION,NaN,[Données non publiées]
94,121,7820,NEANT,Retraitée,NEANT,CREATION,NaN,[Données non publiées]
95,122,3246,RESPONSABLE [Données non publiées],NaN,PPG INDUSTRIES,CREATION,NaN,[Données non publiées]
96,123,5288,Ingénieure territoriale,Mise en disponibilité à compter du 1er mars 20...,Département [Données non publiées],CREATION,NaN,[Données non publiées]
97,124,6658,Réalisation d'éléments en béton,"Actuellement en micro-entreprise, le statut de...",Activité individuelle : statut Micro-entreprise,CREATION,NaN,[Données non publiées]
98,125,596,Chargée de mission [Données non publiées],NaN,GEIE GECOTTI-PE,CREATION,NaN,[Données non publiées]
99,126,7599,Directeur commercial,NaN,SA GERFLOR,CREATION,NaN,[Données non publiées]

In [70]:
activProfConjointDto['id_declaration'].unique().shape

(7434,)

In [71]:
# export en csv
activProfConjointDto.to_csv(folder_export + 'activProfConjointDto.csv', index=False)

## Table mandatElectifDto 
Table des différents mandats électifs déclarés lors de la déclaration

In [72]:
# les chemins qui vont déterminer les champs de la table mandat électif sont les chemins contenant mandat électif
# mais pas montant, cela sera pour la table des ressources
# concretement voici le code
mask_champs_mandatElectifDto = (data3['chemins'].str.contains('mandatElectifDto/items/', na=False)) & ~(data3['chemins'].str.contains('montant/', na=False))

champs_mandatElectifDto = data3[mask_champs_mandatElectifDto]['chemins'].unique()
champs_mandatElectifDto

array(['mandatElectifDto/items/items/motif/id',
       'mandatElectifDto/items/items/commentaire',
       'mandatElectifDto/items/items/descriptionMandat',
       'mandatElectifDto/items/items/remuneration/brutNet',
       'mandatElectifDto/items/items/dateDebut',
       'mandatElectifDto/items/items/dateFin',
       'mandatElectifDto/items/items/conservee',
       'mandatElectifDto/items/items/motif/label'], dtype=object)

In [73]:
# creation de la table
mandatElectifDto = data3[data3['chemins'].isin(champs_mandatElectifDto)][['id_declaration', 'champs', 'valeurs']]
mandatElectifDto.head()

,id_declaration,champs,valeurs
27,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
28,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,REVENUS NETS IMPOSABLES [Données non pu...
29,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,DEPUTE
31,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net
51,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,01/2017

In [74]:
# encodage id_declaration
mandatElectifDto['id_declaration'] = encoder_id_declaration.transform(mandatElectifDto['id_declaration'])

In [75]:
# ajout de l'id_mandat
ids_mandat1 = []
champs_mandat1 = []

# creation de l'id_mandat, qui s'incrémente à chaque nouveau mandat, chaque nouveau id dans le tableau
for element in tqdm(mandatElectifDto['champs'].values):
    champs_mandat1.append(element)
    i = f'm{champs_mandat1.count("id") - 1}'
    ids_mandat1.append(i)

100%|█████████████████████████████████████████████████████████████████████████| 151539/151539 [02:33<00:00, 984.66it/s]

In [76]:
mandatElectifDto['id_mandat'] = ids_mandat1
mandatElectifDto.head(100)

,id_declaration,champs,valeurs,id_mandat
27,2914,id,CREATION,m0
28,2914,commentaire,REVENUS NETS IMPOSABLES [Données non pu...,m0
29,2914,descriptionMandat,DEPUTE,m0
31,2914,brutNet,Net,m0
51,2914,dateDebut,01/2017,m0
54,2914,id,CREATION,m1
55,2914,commentaire,REVENUS NETS IMPOSABLES [Données non pu...,m1
56,2914,descriptionMandat,PRESIDENT DU DEPARTEMENT 01,m1
58,2914,brutNet,Net,m1
69,2914,dateDebut,04/2015,m1
70,2914,dateFin,07/2017,m1
73,2914,id,CREATION,m2
74,2914,commentaire,J'ai été élu président de groupe LR le 6 Novem...,m2
75,2914,descriptionMandat,Président du Groupe Les Républicains à l'Assem...,m2
77,2914,brutNet,Net,m2
91,2914,dateDebut,11/2019,m2
92,2914,dateFin,05/2022,m2
95,2914,id,CREATION,m3
96,2914,commentaire,[Données non publiées],m3
97,2914,descriptionMandat,CONSEILLER DEPARTEMENTAL,m3
99,2914,brutNet,Net,m3
119,2914,dateDebut,07/2017,m3
122,2914,id,CREATION,m4
123,2914,descriptionMandat,Département de l'Ain - Président du Groupe maj...,m4
125,2914,brutNet,Net,m4
145,2914,dateDebut,07/2017,m4
406,10647,id,CREATION,m5
407,10647,commentaire,REVENUS NETS IMPOSABLES [Données non pu...,m5
408,10647,descriptionMandat,DEPUTE,m5
410,10647,brutNet,Net,m5
430,10647,dateDebut,01/2017,m5
433,10647,id,CREATION,m6
434,10647,commentaire,REVENUS NETS IMPOSABLES [Données non pu...,m6
435,10647,descriptionMandat,PRESIDENT DU DEPARTEMENT 01,m6
437,10647,brutNet,Net,m6
448,10647,dateDebut,04/2015,m6
449,10647,dateFin,07/2017,m6
452,10647,id,CREATION,m7
453,10647,commentaire,J'ai été élu président de groupe LR le 6 Novem...,m7
454,10647,descriptionMandat,Président du Groupe Les Républicains à l'Assem...,m7
456,10647,brutNet,Net,m7
470,10647,dateDebut,11/2019,m7
471,10647,dateFin,05/2022,m7
474,10647,id,CREATION,m8
475,10647,commentaire,[Données non publiées],m8
476,10647,descriptionMandat,CONSEILLER DEPARTEMENTAL,m8
478,10647,brutNet,Net,m8
498,10647,dateDebut,07/2017,m8
501,10647,id,CREATION,m9
502,10647,descriptionMandat,Département de l'Ain - Président du Groupe maj...,m9
504,10647,brutNet,Net,m9
524,10647,dateDebut,07/2017,m9
525,10647,dateFin,10/2022,m9
827,1458,id,CREATION,m10
828,1458,commentaire,rémunération 2022 en cours.,m10
829,1458,conservee,true,m10
830,1458,descriptionMandat,DEPUTE,m10
832,1458,brutNet,Net,m10
852,1458,dateDebut,06/2017,m10
1030,8289,id,CREATION,m11
1031,8289,commentaire,rémunération 2022 en cours.,m11
1032,8289,conservee,true,m11
1033,8289,descriptionMandat,DEPUTE,m11
1035,8289,brutNet,Net,m11
1055,8289,dateDebut,06/2017,m11
1235,7293,id,CREATION,m12
1236,7293,descriptionMandat,Maire,m12
1238,7293,brutNet,Net,m12
1246,7293,dateDebut,05/2020,m12
1373,4188,id,CREATION,m13
1374,4188,commentaire,j ai été élue en juin donc je continue mon mandat,m13
1375,4188,descriptionMandat,conseil departemental,m13
1377,4188,brutNet,Net,m13
1400,4188,dateDebut,03/2015,m13
1401,4188,dateFin,06/2021,m13
1404,4188,id,CREATION,m14
1405,4188,commentaire,je suis à ce jour toujours maire,m14
1406,4188,descriptionMandat,maire,m14
1408,4188,brutNet,Net,m14
1416,4188,dateDebut,06/2020,m14
1417,4188,dateFin,07/2021,m14
1420,4188,id,CREATION,m15
1421,4188,commentaire,je suis a ce jour toujours conseillère communa...,m15
1422,4188,descriptionMandat,conseillère communautaire,m15
1424,4188,brutNet,Net,m15
1432,4188,dateDebut,07/2020,m15
1433,4188,dateFin,07/2021,m15
1533,6865,id,CREATION,m16
1534,6865,commentaire,net perçu avant prélèvement ou impôts2021: à f...,m16
1535,6865,descriptionMandat,Maire de Fains-Véel,m16
1537,6865,brutNet,Net,m16
1560,6865,dateDebut,01/2015,m16
1561,6865,dateFin,06/2021,m16
1564,6865,id,CREATION,m17
1565,6865,descriptionMandat,Vice-Président de la Communauté d'Agglomératio...,m17
1567,6865,brutNet,Net,m17
1590,6865,dateDebut,01/2015,m17
1591,6865,dateFin,06/2021,m17
1594,6865,id,CREATION,m18
1595,6865,commentaire,"Perçu avant impôts, idem autres mlandats",m18

In [77]:
# supression des doublons
mandatElectifDto = mandatElectifDto.drop(mandatElectifDto[mandatElectifDto.duplicated(subset=['id_declaration','champs', 'id_mandat'],
                                                                                                      keep='last')].index)

In [78]:
mandatElectifDto = mandatElectifDto.pivot(index=['id_declaration', 'id_mandat'],
                                          columns='champs', values='valeurs').reset_index()
mandatElectifDto.head()

champs,id_declaration,id_mandat,brutNet,commentaire,conservee,dateDebut,dateFin,descriptionMandat,id,label
0,0,m8012,Net,Somme des montants nets avant impôts des mois ...,NaN,03/2020,05/2020,Maire de La Celle Saint-Cloud,CREATION,NaN
1,0,m8013,Net,Somme des montants nets avant impôts des mois ...,NaN,03/2020,05/2020,Vice-président de la communauté d'agglomératio...,CREATION,NaN
2,2,m21205,Brut,NaN,NaN,01/2012,07/2017,VICE PRESIDENT D'UN SYNDICAT D'ELECTRIFICATION,CREATION,NaN
3,2,m21206,Brut,NaN,NaN,01/2013,12/2016,PRESIDENT DU CONSEIL GENERAL,CREATION,NaN
4,2,m21207,Brut,NaN,NaN,01/2013,12/2016,ADJOINT MAIRIE,CREATION,NaN

In [81]:
mandatElectifDto[mandatElectifDto['id']=='néant']

Empty DataFrame
Columns: [id_declaration, id_mandat, brutNet, commentaire, conservee, dateDebut, dateFin, descriptionMandat, id, label]
Index: []

In [242]:
mandatElectifDto[mandatElectifDto['id_declaration']==2914]

champs,id_declaration,id_mandat,brutNet,commentaire,conservee,dateDebut,dateFin,descriptionMandat,id,label,neant
7964,2914,m0,Net,REVENUS NETS IMPOSABLES [Données non pu...,NaN,01/2017,NaN,DEPUTE,CREATION,NaN,NaN
7965,2914,m1,Net,REVENUS NETS IMPOSABLES [Données non pu...,NaN,04/2015,07/2017,PRESIDENT DU DEPARTEMENT 01,CREATION,NaN,NaN
7966,2914,m2,Net,J'ai été élu président de groupe LR le 6 Novem...,NaN,11/2019,05/2022,Président du Groupe Les Républicains à l'Assem...,CREATION,NaN,NaN
7967,2914,m3,Net,[Données non publiées],NaN,07/2017,NaN,CONSEILLER DEPARTEMENTAL,CREATION,NaN,NaN
7968,2914,m4,Net,NaN,NaN,07/2017,NaN,Département de l'Ain - Président du Groupe maj...,CREATION,NaN,false

In [290]:
# export en csv
mandatElectifDto.to_csv(folder_export + 'mandatElectifDto.csv', index=False)

## Table ressources

In [243]:
# conditions de mapping entre le chemin xml et les champs de la table en cours
mask_champs_ressources = (data3['chemins'].str.contains('mandatElectifDto/items/', na=False))

champs_ressources = data3[mask_champs_ressources]['chemins'].unique()
champs_ressources

array(['mandatElectifDto/items/items/motif/id',
       'mandatElectifDto/items/items/commentaire',
       'mandatElectifDto/items/items/descriptionMandat',
       'mandatElectifDto/items/items/remuneration/brutNet',
       'mandatElectifDto/items/items/remuneration/montant/montant/annee',
       'mandatElectifDto/items/items/remuneration/montant/montant/montant',
       'mandatElectifDto/items/items/dateDebut',
       'mandatElectifDto/items/items/dateFin', 'mandatElectifDto/neant',
       'mandatElectifDto/items/items/conservee',
       'mandatElectifDto/items/items/motif/label'], dtype=object)

In [245]:
# creation de la table
ressources = data3[data3['chemins'].isin(champs_ressources)][['id_declaration', 'champs', 'valeurs']]
ressources.head(100)

,id_declaration,champs,valeurs
27,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
28,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,REVENUS NETS IMPOSABLES [Données non pu...
29,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,DEPUTE
31,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net
34,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017
35,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,67 047
37,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2018
38,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,71 042
40,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019
41,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,71 105
43,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020
44,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,70 773
46,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021
47,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,70 676
49,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022
50,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,27 289
51,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,01/2017
54,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
55,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,REVENUS NETS IMPOSABLES [Données non pu...
56,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,PRESIDENT DU DEPARTEMENT 01
58,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net
61,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2015
62,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16865
64,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2016
65,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,23035
67,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017
68,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,20120
69,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,04/2015
70,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,07/2017
73,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
74,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,J'ai été élu président de groupe LR le 6 Novem...
75,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,Président du Groupe Les Républicains à l'Assem...
77,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net
80,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019
81,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
83,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020
84,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
86,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021
87,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
89,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022
90,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
91,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,11/2019
92,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,05/2022
95,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
96,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,[Données non publiées]
97,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,CONSEILLER DEPARTEMENTAL
99,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net
102,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017
103,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,28 007
105,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2018
106,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,24 201
108,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019
109,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16 386
111,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020
112,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16 386
114,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021
115,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16 384
117,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022
118,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,6 827
119,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,07/2017
122,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
123,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,Département de l'Ain - Président du Groupe maj...
125,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net
128,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017
129,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
131,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2018
132,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
134,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019
135,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
137,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020
138,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
140,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021
141,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
143,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022
144,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
145,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,07/2017
146,4344aaa1-874d-4e6d-9b1a-45f7725b710c,neant,false
406,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,id,CREATION
407,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,commentaire,REVENUS NETS IMPOSABLES [Données non pu...
408,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,descriptionMandat,DEPUTE
410,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,brutNet,Net
413,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2017
414,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,67 047
416,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2018
417,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,71 042
419,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2019
420,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,71 105
422,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2020
423,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,70 773
425,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2021
426,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,70 676
428,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2022
429,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,27 289
430,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,dateDebut,01/2017
433,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,id,CREATION
434,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,commentaire,REVENUS NETS IMPOSABLES [Données non pu...
435,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,descriptionMandat,PRESIDENT DU DEPARTEMENT 01
437,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,brutNet,Net
440,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2015
441,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,16865

In [246]:
ressources.shape

(398693, 3)

In [247]:
# ajout de l'id_mandat
ids_mandat2 = []
champs_mandat2 = []

# creation de l'id_mandat, qui s'incrémente à chaque nouveau mandat, chaque nouveau id dans le tableau
for element in ressources['champs'].values:
    champs_mandat2.append(element)
    i = f'm{champs_mandat2.count("id") - 1}'
    ids_mandat2.append(i)

In [248]:
# creation de la colonne id_activite (car il y a d'autres activités que les mandats) dans ressources, en tant que clé étrangère
ressources['id_activite'] = ids_mandat2
ressources.head(100)

,id_declaration,champs,valeurs,id_activite
27,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,m0
28,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,REVENUS NETS IMPOSABLES [Données non pu...,m0
29,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,DEPUTE,m0
31,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net,m0
34,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,m0
35,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,67 047,m0
37,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2018,m0
38,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,71 042,m0
40,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019,m0
41,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,71 105,m0
43,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020,m0
44,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,70 773,m0
46,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021,m0
47,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,70 676,m0
49,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022,m0
50,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,27 289,m0
51,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,01/2017,m0
54,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,m1
55,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,REVENUS NETS IMPOSABLES [Données non pu...,m1
56,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,PRESIDENT DU DEPARTEMENT 01,m1
58,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net,m1
61,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2015,m1
62,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16865,m1
64,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2016,m1
65,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,23035,m1
67,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,m1
68,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,20120,m1
69,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,04/2015,m1
70,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,07/2017,m1
73,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,m2
74,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,J'ai été élu président de groupe LR le 6 Novem...,m2
75,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,Président du Groupe Les Républicains à l'Assem...,m2
77,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net,m2
80,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019,m2
81,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m2
83,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020,m2
84,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m2
86,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021,m2
87,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m2
89,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022,m2
90,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m2
91,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,11/2019,m2
92,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,05/2022,m2
95,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,m3
96,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,[Données non publiées],m3
97,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,CONSEILLER DEPARTEMENTAL,m3
99,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net,m3
102,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,m3
103,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,28 007,m3
105,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2018,m3
106,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,24 201,m3
108,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019,m3
109,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16 386,m3
111,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020,m3
112,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16 386,m3
114,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021,m3
115,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16 384,m3
117,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022,m3
118,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,6 827,m3
119,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,07/2017,m3
122,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,m4
123,4344aaa1-874d-4e6d-9b1a-45f7725b710c,descriptionMandat,Département de l'Ain - Président du Groupe maj...,m4
125,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net,m4
128,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,m4
129,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4
131,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2018,m4
132,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4
134,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019,m4
135,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4
137,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020,m4
138,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4
140,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021,m4
141,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4
143,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022,m4
144,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4
145,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,07/2017,m4
146,4344aaa1-874d-4e6d-9b1a-45f7725b710c,neant,false,m4
406,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,id,CREATION,m5
407,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,commentaire,REVENUS NETS IMPOSABLES [Données non pu...,m5
408,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,descriptionMandat,DEPUTE,m5
410,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,brutNet,Net,m5
413,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2017,m5
414,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,67 047,m5
416,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2018,m5
417,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,71 042,m5
419,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2019,m5
420,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,71 105,m5
422,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2020,m5
423,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,70 773,m5
425,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2021,m5
426,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,70 676,m5
428,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2022,m5
429,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,27 289,m5
430,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,dateDebut,01/2017,m5
433,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,id,CREATION,m6
434,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,commentaire,REVENUS NETS IMPOSABLES [Données non pu...,m6
435,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,descriptionMandat,PRESIDENT DU DEPARTEMENT 01,m6
437,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,brutNet,Net,m6
440,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2015,m6
441,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,16865,m6

In [249]:
# suppression des colonnes qui ne sont pas des ressources
ressources = ressources[ressources['champs'].isin(['annee', 'montant'])]
ressources.head()

                          id_declaration   champs valeurs id_activite
34  4344aaa1-874d-4e6d-9b1a-45f7725b710c    annee    2017          m0
35  4344aaa1-874d-4e6d-9b1a-45f7725b710c  montant  67 047          m0
37  4344aaa1-874d-4e6d-9b1a-45f7725b710c    annee    2018          m0
38  4344aaa1-874d-4e6d-9b1a-45f7725b710c  montant  71 042          m0
40  4344aaa1-874d-4e6d-9b1a-45f7725b710c    annee    2019          m0

In [250]:
# ajout de l'id_ressources
ids_ressources = []
champs_ressources = []

# creation de l'id_ressources, qui s'incrémente à chaque nouvelle année
for element in ressources['champs'].values:
    champs_ressources.append(element)
    i = champs_ressources.count("annee") - 1
    ids_ressources.append(i)

In [251]:
# creation de la colonne id_ressources dans ressources, en tant que clé primaire
ressources['id_ressource'] = ids_ressources
ressources.head(100)

,id_declaration,champs,valeurs,id_activite,id_ressource
34,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,m0,0
35,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,67 047,m0,0
37,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2018,m0,1
38,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,71 042,m0,1
40,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019,m0,2
41,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,71 105,m0,2
43,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020,m0,3
44,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,70 773,m0,3
46,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021,m0,4
47,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,70 676,m0,4
49,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022,m0,5
50,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,27 289,m0,5
61,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2015,m1,6
62,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16865,m1,6
64,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2016,m1,7
65,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,23035,m1,7
67,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,m1,8
68,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,20120,m1,8
80,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019,m2,9
81,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m2,9
83,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020,m2,10
84,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m2,10
86,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021,m2,11
87,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m2,11
89,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022,m2,12
90,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m2,12
102,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,m3,13
103,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,28 007,m3,13
105,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2018,m3,14
106,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,24 201,m3,14
108,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019,m3,15
109,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16 386,m3,15
111,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020,m3,16
112,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16 386,m3,16
114,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021,m3,17
115,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,16 384,m3,17
117,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022,m3,18
118,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,6 827,m3,18
128,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,m4,19
129,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4,19
131,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2018,m4,20
132,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4,20
134,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2019,m4,21
135,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4,21
137,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2020,m4,22
138,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4,22
140,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2021,m4,23
141,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4,23
143,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2022,m4,24
144,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,m4,24
413,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2017,m5,25
414,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,67 047,m5,25
416,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2018,m5,26
417,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,71 042,m5,26
419,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2019,m5,27
420,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,71 105,m5,27
422,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2020,m5,28
423,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,70 773,m5,28
425,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2021,m5,29
426,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,70 676,m5,29
428,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2022,m5,30
429,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,27 289,m5,30
440,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2015,m6,31
441,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,16865,m6,31
443,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2016,m6,32
444,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,23035,m6,32
446,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2017,m6,33
447,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,20120,m6,33
459,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2019,m7,34
460,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m7,34
462,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2020,m7,35
463,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m7,35
465,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2021,m7,36
466,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m7,36
468,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2022,m7,37
469,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m7,37
481,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2017,m8,38
482,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,28 007,m8,38
484,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2018,m8,39
485,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,24 201,m8,39
487,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2019,m8,40
488,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,16 386,m8,40
490,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2020,m8,41
491,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,16 386,m8,41
493,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2021,m8,42
494,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,16 384,m8,42
496,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2022,m8,43
497,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,6 827,m8,43
507,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2017,m9,44
508,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m9,44
510,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2018,m9,45
511,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m9,45
513,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2019,m9,46
514,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m9,46
516,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2020,m9,47
517,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m9,47
519,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2021,m9,48
520,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m9,48
522,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,annee,2022,m9,49
523,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,montant,0,m9,49

In [ ]:
ressources = ressources.drop(ressources[ressources.duplicated(subset=['id_declaration',
                                                         'champs', 'id_activite', 'id_ressource'], keep=False)].index)

In [253]:
# pivot de la table ressources
ressources = ressources.pivot(index=['id_declaration', 'id_activite', 'id_ressource'],
                                          columns='champs', values='valeurs').reset_index()
ressources.head(100)

champs,id_declaration,id_activite,id_ressource,annee,montant
0,000765d9-da68-48c6-a95d-f34a12cacb5f,m8012,34173,2020,6556
1,000765d9-da68-48c6-a95d-f34a12cacb5f,m8013,34174,2020,3180
2,0014115c-cbae-4bdd-98d1-39c8e6062095,m21205,89421,2012,0
3,0014115c-cbae-4bdd-98d1-39c8e6062095,m21205,89422,2013,7200
4,0014115c-cbae-4bdd-98d1-39c8e6062095,m21205,89423,2014,5820
5,0014115c-cbae-4bdd-98d1-39c8e6062095,m21205,89424,2015,5280
6,0014115c-cbae-4bdd-98d1-39c8e6062095,m21205,89425,2016,5298
7,0014115c-cbae-4bdd-98d1-39c8e6062095,m21205,89426,2017,2640
8,0014115c-cbae-4bdd-98d1-39c8e6062095,m21206,89427,2013,59300
9,0014115c-cbae-4bdd-98d1-39c8e6062095,m21206,89428,2014,59300
10,0014115c-cbae-4bdd-98d1-39c8e6062095,m21206,89429,2015,62300
11,0014115c-cbae-4bdd-98d1-39c8e6062095,m21206,89430,2016,64000
12,0014115c-cbae-4bdd-98d1-39c8e6062095,m21207,89431,2013,3000
13,0014115c-cbae-4bdd-98d1-39c8e6062095,m21207,89432,2014,3000
14,0014115c-cbae-4bdd-98d1-39c8e6062095,m21207,89433,2015,3000
15,0014115c-cbae-4bdd-98d1-39c8e6062095,m21207,89434,2016,3000
16,0014115c-cbae-4bdd-98d1-39c8e6062095,m21208,89435,2013,7500
17,0014115c-cbae-4bdd-98d1-39c8e6062095,m21208,89436,2014,7500
18,0014115c-cbae-4bdd-98d1-39c8e6062095,m21208,89437,2015,7500
19,0014115c-cbae-4bdd-98d1-39c8e6062095,m21208,89438,2016,7500
20,0014115c-cbae-4bdd-98d1-39c8e6062095,m21209,89439,2013,5800
21,0014115c-cbae-4bdd-98d1-39c8e6062095,m21209,89440,2014,5800
22,0014115c-cbae-4bdd-98d1-39c8e6062095,m21209,89441,2015,5800
23,0014115c-cbae-4bdd-98d1-39c8e6062095,m21209,89442,2016,5800
24,0014115c-cbae-4bdd-98d1-39c8e6062095,m21210,89443,2017,2 675
25,0014115c-cbae-4bdd-98d1-39c8e6062095,m21210,89444,2018,5 318
26,0014115c-cbae-4bdd-98d1-39c8e6062095,m21210,89445,2019,3 734
27,0014115c-cbae-4bdd-98d1-39c8e6062095,m21210,89446,2020,3 583
28,0014115c-cbae-4bdd-98d1-39c8e6062095,m21210,89447,2021,2 672
29,0014115c-cbae-4bdd-98d1-39c8e6062095,m21211,89448,2017,45 719
30,0014115c-cbae-4bdd-98d1-39c8e6062095,m21211,89449,2018,65 026
31,0014115c-cbae-4bdd-98d1-39c8e6062095,m21211,89450,2019,41 619
32,0014115c-cbae-4bdd-98d1-39c8e6062095,m21211,89451,2020,41 011
33,0014115c-cbae-4bdd-98d1-39c8e6062095,m21211,89452,2021,20 505
34,0014115c-cbae-4bdd-98d1-39c8e6062095,m21212,89453,2017,3 064
35,0014115c-cbae-4bdd-98d1-39c8e6062095,m21212,89454,2018,3 065
36,0014115c-cbae-4bdd-98d1-39c8e6062095,m21212,89455,2019,1 994
37,0014115c-cbae-4bdd-98d1-39c8e6062095,m21212,89456,2020,2 664
38,0014115c-cbae-4bdd-98d1-39c8e6062095,m21212,89457,2021,1 622
39,0014115c-cbae-4bdd-98d1-39c8e6062095,m21213,89458,2017,0
40,0014115c-cbae-4bdd-98d1-39c8e6062095,m21213,89459,2018,0
41,0014115c-cbae-4bdd-98d1-39c8e6062095,m21213,89460,2019,3 980
42,0014115c-cbae-4bdd-98d1-39c8e6062095,m21213,89461,2020,3 573
43,0014115c-cbae-4bdd-98d1-39c8e6062095,m21213,89462,2021,2 300
44,0014115c-cbae-4bdd-98d1-39c8e6062095,m21214,89463,2017,5 919
45,0014115c-cbae-4bdd-98d1-39c8e6062095,m21214,89464,2018,5 922
46,0014115c-cbae-4bdd-98d1-39c8e6062095,m21214,89465,2019,1 423
47,0014115c-cbae-4bdd-98d1-39c8e6062095,m21214,89466,2020,1 477
48,0014115c-cbae-4bdd-98d1-39c8e6062095,m21214,89467,2021,1 103
49,0014115c-cbae-4bdd-98d1-39c8e6062095,m21215,89468,2017,29 895
50,0014115c-cbae-4bdd-98d1-39c8e6062095,m21215,89469,2018,3 326
51,0014115c-cbae-4bdd-98d1-39c8e6062095,m21215,89470,2019,3 452
52,0014115c-cbae-4bdd-98d1-39c8e6062095,m21215,89471,2020,3 463
53,0014115c-cbae-4bdd-98d1-39c8e6062095,m21215,89472,2021,1 679
54,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11279,48124,2020,0
55,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11280,48125,2020,0
56,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11281,48126,2015,49 826
57,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11281,48127,2016,49 822
58,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11281,48128,2017,67 438
59,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11281,48129,2018,72 674
60,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11281,48130,2019,74 981
61,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11281,48131,2020,77 083
62,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11282,48132,2015,21 399
63,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11282,48133,2016,21 406
64,0020c869-c893-40ff-b7c4-42aeb8f6d1c0,m11282,48134,2017,22 576
65,00243ad5-2191-4efc-884b-df9213413b17,m16136,67704,2015,28875
66,00243ad5-2191-4efc-884b-df9213413b17,m16136,67705,2016,36936
67,00243ad5-2191-4efc-884b-df9213413b17,m16136,67706,2017,33858
68,00243ad5-2191-4efc-884b-df9213413b17,m16136,67707,2018,42 849
69,00243ad5-2191-4efc-884b-df9213413b17,m16136,67708,2019,31 154
70,00243ad5-2191-4efc-884b-df9213413b17,m16136,67709,2020,31 681
71,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16253,68053,2020,31 201
72,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16253,68054,2021,2 730
73,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16254,68055,2015,29 843
74,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16254,68056,2016,31 978
75,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16254,68057,2017,32 110
76,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16254,68058,2018,31 406
77,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16254,68059,2019,29 302
78,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16254,68060,2020,30 283
79,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16254,68061,2021,2 994
80,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16255,68062,2020,25 244
81,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,m16255,68063,2021,2 729
82,0037f81f-6f0f-4179-86ef-1490201c15c1,m4203,18321,2020,8 300
83,0037f81f-6f0f-4179-86ef-1490201c15c1,m4203,18322,2021,9 779
84,0037f81f-6f0f-4179-86ef-1490201c15c1,m4204,18323,2020,21 000
85,0037f81f-6f0f-4179-86ef-1490201c15c1,m4204,18324,2021,14 000
86,0037f81f-6f0f-4179-86ef-1490201c15c1,m4205,18325,2021,8 288
87,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1275,5307,2014,51689
88,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1275,5308,2015,22016
89,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1275,5309,2016,22971
90,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1275,5310,2017,17189
91,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1275,5311,2018,17573
92,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1275,5312,2019,17 600
93,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1275,5313,2020,16 200
94,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1276,5314,2014,66145
95,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1276,5315,2015,66145
96,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1276,5316,2016,50551
97,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1276,5317,2017,51067
98,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1276,5318,2018,51092
99,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,m1276,5319,2019,52 366

In [259]:
ressources.shape

(118181, 5)

In [272]:
# encodage id_declaration
ressources['id_declaration'] = encoder_id_declaration.transform(ressources['id_declaration'])

In [120]:
ressources.head()

NameError: name 'ressources' is not defined

In [291]:
# export en csv
ressources.to_csv(folder_export + 'ressources1.csv', index=False)

## Table participationDirigeantDto

In [369]:
# conditions de mapping entre le chemin xml et les champs de la table en cours
mask_participationDirigeantDto = (data3['chemins'].str.contains('participationDirigeantDto/items/', na=False)) & ~(data3['chemins'].str.contains('montant/', na=False))

champs_participationDirigeantDto = data3[mask_participationDirigeantDto]['chemins'].unique()

In [370]:
champs_participationDirigeantDto

array(['participationDirigeantDto/items/items/motif/id',
       'participationDirigeantDto/items/items/commentaire',
       'participationDirigeantDto/items/items/nomSociete',
       'participationDirigeantDto/items/items/activite',
       'participationDirigeantDto/items/items/remuneration/brutNet',
       'participationDirigeantDto/items/items/dateDebut',
       'participationDirigeantDto/items/items/dateFin',
       'participationDirigeantDto/items/items/conservee',
       'participationDirigeantDto/items/items/motif/label'], dtype=object)

In [371]:
# creation de la table
participationDirigeantDto = data3[data3['chemins'].isin(champs_participationDirigeantDto)][['id_declaration', 'champs', 'valeurs']]
participationDirigeantDto.head(20)

,id_declaration,champs,valeurs
151,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
152,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Président du SDIS 01. Activité arrêtée depuis ...
153,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,SDIS 01
154,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Service départemental d'incendie et de secours
156,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Brut
167,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,04/2015
168,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,07/2017
171,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
172,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Président de l'association AINTOURISME qui dév...
173,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,ASSOCIATION AINTOURISME
174,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Président d'Aintourisme qui a pour objet la po...
176,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net
196,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,07/2017
199,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
200,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Mon élection comme président du groupe LR à l'...
201,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,Assemblée nationale - Groupe Les Républicains -
202,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Président du Groupe Les Républicains à l'Assem...
204,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net
218,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,11/2019
219,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,05/2022

In [372]:
participationDirigeantDto.shape

(317798, 3)

In [373]:
# ajout de l'id_dirigeant
ids_part_dir1 = []
champs_part_dir1 = []

# creation de l'id_dirigeant, qui s'incrémente à chaque nouvelle activité, chaque nouveau id dans le tableau
for element in tqdm(participationDirigeantDto['champs'].values):
    champs_part_dir1.append(element)
    i = f'd{champs_part_dir1.count("id") - 1}'
    ids_part_dir1.append(i)

100%|█████████████████████████████████████████████████████████████████████████| 317798/317798 [10:52<00:00, 486.69it/s]

In [374]:
participationDirigeantDto['id_dirigeant'] = ids_part_dir1
participationDirigeantDto.head(20)

,id_declaration,champs,valeurs,id_dirigeant
151,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,d0
152,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Président du SDIS 01. Activité arrêtée depuis ...,d0
153,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,SDIS 01,d0
154,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Service départemental d'incendie et de secours,d0
156,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Brut,d0
167,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,04/2015,d0
168,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,07/2017,d0
171,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,d1
172,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Président de l'association AINTOURISME qui dév...,d1
173,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,ASSOCIATION AINTOURISME,d1
174,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Président d'Aintourisme qui a pour objet la po...,d1
176,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net,d1
196,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,07/2017,d1
199,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,d2
200,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Mon élection comme président du groupe LR à l'...,d2
201,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,Assemblée nationale - Groupe Les Républicains -,d2
202,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Président du Groupe Les Républicains à l'Assem...,d2
204,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net,d2
218,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,11/2019,d2
219,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,05/2022,d2

In [375]:
# suppression des doublons pour le pivot
participationDirigeantDto = participationDirigeantDto.drop(participationDirigeantDto[participationDirigeantDto.duplicated(subset=['id_declaration',
                                                                                                                                  'champs', 'id_dirigeant'], keep='last')].index)

In [376]:
# pivot de la table
participationDirigeantDto = participationDirigeantDto.pivot(index=['id_declaration', 'id_dirigeant'],
                                          columns='champs', values='valeurs').reset_index()
participationDirigeantDto.head(100)

champs,id_declaration,id_dirigeant,activite,brutNet,commentaire,conservee,dateDebut,dateFin,id,label,nomSociete
0,0014115c-cbae-4bdd-98d1-39c8e6062095,d39447,Président,Brut,PAS DE REMUNERATION,NaN,01/2012,07/2017,CREATION,NaN,SEMAP
1,0014115c-cbae-4bdd-98d1-39c8e6062095,d39448,Président,Brut,Pas de rémunération,NaN,01/2012,07/2017,CREATION,NaN,SEMIP
2,0014115c-cbae-4bdd-98d1-39c8e6062095,d39449,Président,Brut,Pas de rémunération,NaN,01/2012,07/2017,CREATION,NaN,SEM N'PY
3,0014115c-cbae-4bdd-98d1-39c8e6062095,d39450,Président,Brut,Pas de rémunération,NaN,01/2012,07/2017,CREATION,NaN,SPL BALNEA
4,0014115c-cbae-4bdd-98d1-39c8e6062095,d39451,PRESIDENT,Brut,PAS DE REMUNERATION PAS DE GRATIFICATION,NaN,01/2011,12/2016,CREATION,NaN,PROMODEF
5,0014115c-cbae-4bdd-98d1-39c8e6062095,d39452,PRESIDENT,Net,PAS DE REMUNERATION,NaN,01/2017,06/2021,CREATION,NaN,SPL PEYRAGUDES
6,0014115c-cbae-4bdd-98d1-39c8e6062095,d39453,PRESIDENT,Net,PAS DE REMUNERATION,NaN,01/2017,06/2021,CREATION,NaN,SEMIP
7,0014115c-cbae-4bdd-98d1-39c8e6062095,d39454,PRESIDENT,Net,FIN DE MANDAT 2019,NaN,01/2017,12/2019,CREATION,NaN,SEM N'PY
8,0014115c-cbae-4bdd-98d1-39c8e6062095,d39455,PRESIDENT,Net,PAS DE REMUNERATION,NaN,01/2017,06/2021,CREATION,NaN,SPL BALNEA
9,0014115c-cbae-4bdd-98d1-39c8e6062095,d39456,PRESIDENT,Net,PAS DE REMUNERATION FIN DE MANDAT 2020,NaN,01/2017,06/2020,CREATION,NaN,PROMODEF
10,00243ad5-2191-4efc-884b-df9213413b17,d28828,vice présidente,Net,NaN,NaN,11/2019,NaN,CREATION,NaN,association Cinetheact
11,00243ad5-2191-4efc-884b-df9213413b17,d28829,présidente,Net,NaN,NaN,11/2015,NaN,CREATION,NaN,Idefhi
12,00243ad5-2191-4efc-884b-df9213413b17,d28830,Presidente,Net,NaN,NaN,06/2015,NaN,CREATION,NaN,etablissement public Grugny
13,002c2aae-c0e3-4056-8e4b-a804f56a9d25,d12947,Cogérante,Net,gérante (mandat bénévole)salariée parallèlemen...,NaN,06/2016,06/2019,CREATION,NaN,La Coopérative Tiers-Lieux
14,002c2aae-c0e3-4056-8e4b-a804f56a9d25,d12948,Secrétaire générale,Net,association loi 1901,NaN,08/2019,12/2021,CREATION,NaN,France Tiers-Lieux
15,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,d29070,membre commission consultative environnement,Net,non rémunéré,NaN,03/2020,NaN,CREATION,NaN,Aéroport Marseille Provence
16,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,d29071,Président Conseil Administration,Net,non rémunéré,NaN,03/2020,NaN,CREATION,NaN,EPAHD
17,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,d29072,Membre conseil administration,Net,non rémunéré,NaN,03/2020,NaN,CREATION,NaN,Régie Halle des Sports Miramas
18,002e21a3-a6cc-4861-8a01-f1f2b01e9d6f,d29073,membre conseil administration,Net,non rémunéré,NaN,03/2020,NaN,CREATION,NaN,SDIS Bouches du Rhône ( Pompiers)
19,003520eb-099d-47f3-aee1-1df686ed1ae8,d16160,présidence,Net,L'Orchestre français des jeunes est une associ...,NaN,06/2021,NaN,CREATION,NaN,Orchestre français des jeunes
20,003520eb-099d-47f3-aee1-1df686ed1ae8,d16161,administratrice,Net,ProQuartet est une association Loi de 1901 qui...,NaN,01/2016,NaN,CREATION,NaN,ProQuartet
21,003520eb-099d-47f3-aee1-1df686ed1ae8,d16162,administratrice,Net,L'association des musées d'Espalion gère le mu...,NaN,01/2016,NaN,CREATION,NaN,Association des musées d'Espalion
22,003520eb-099d-47f3-aee1-1df686ed1ae8,d16163,gérante,Net,[Données non publiées],NaN,01/2016,NaN,CREATION,NaN,SCI [Données non publiées]
23,0037f81f-6f0f-4179-86ef-1490201c15c1,d7543,SCI propriétaire d'un appartement avec garage,Net,Je suis cogérant de cette SCI qui existe toujo...,NaN,01/2018,12/2020,CREATION,NaN,SCI [Données non publiées]
24,0037f81f-6f0f-4179-86ef-1490201c15c1,d7544,Agence de communication,Net,Entreprise dormante depuis fin 2016 et radiée ...,NaN,01/2014,06/2019,CREATION,NaN,BRC Partners
25,0037f81f-6f0f-4179-86ef-1490201c15c1,d7545,Président du CCAS Ville de Bron,Net,NaN,NaN,07/2020,NaN,CREATION,NaN,CCAS Ville de Bron
26,0037f81f-6f0f-4179-86ef-1490201c15c1,d7546,Syndicat intercommunal de gestion des énergies...,Net,NaN,NaN,07/2020,NaN,CREATION,NaN,SYGERLy
27,003d375a-3bf4-4441-817e-8593c32e7d57,d33519,Membre du Conseil d'Administration,Net,NaN,NaN,06/2016,06/2019,CREATION,NaN,Outdoor Sport Sports Valley
28,003d375a-3bf4-4441-817e-8593c32e7d57,d33520,Membre du Conseil d'Administration,Net,NaN,NaN,09/2016,12/2020,CREATION,NaN,1% For the Planet France
29,003d375a-3bf4-4441-817e-8593c32e7d57,d33521,Membre du Conseil d'administration,Net,NaN,NaN,01/2014,06/2015,CREATION,NaN,Prioriterre
30,003d375a-3bf4-4441-817e-8593c32e7d57,d33522,Membre du Conseil d'administration et Président,Net,NaN,NaN,01/2014,03/2015,CREATION,NaN,Roule & Co
31,003d375a-3bf4-4441-817e-8593c32e7d57,d33523,Co-gérant,Net,J'ai mis les même montant que ma rémunération ...,NaN,01/2014,07/2020,CREATION,NaN,AIR coop
32,003d5e30-d8be-49de-a8ca-de718750a615,d28128,Président,Brut,NaN,false,02/2012,10/2014,CREATION,NaN,Domaine National de Chambord EPIC
33,003d5e30-d8be-49de-a8ca-de718750a615,d28129,Membre,Brut,NaN,false,10/2012,10/2014,CREATION,NaN,Commission Consultative du Secret de la Défens...
34,003d5e30-d8be-49de-a8ca-de718750a615,d28130,Membre de droit,Brut,NaN,true,01/2011,10/2017,CREATION,NaN,Union des maires des Yvelines
35,003d5e30-d8be-49de-a8ca-de718750a615,d28131,Président,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Comité de Direction de l'Office de tourisme de...
36,003d5e30-d8be-49de-a8ca-de718750a615,d28132,Délégué,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Syndicat Intercommunal d'assainissement de la ...
37,003d5e30-d8be-49de-a8ca-de718750a615,d28133,Délégué,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Syndicat mixte de production d'eau potable de ...
38,003d5e30-d8be-49de-a8ca-de718750a615,d28134,Délégué suppléant,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Syndicat d'energie des Yvelines
39,003d5e30-d8be-49de-a8ca-de718750a615,d28135,Président,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Syndicat Intercommunal de la région de Ramboui...
40,003d5e30-d8be-49de-a8ca-de718750a615,d28136,Président,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Syndicat mixte d'élaboration du schéma de cohé...
41,003d5e30-d8be-49de-a8ca-de718750a615,d28137,Président,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Conseil de surveillance de l'hopital de Rambou...
42,003d5e30-d8be-49de-a8ca-de718750a615,d28138,Président,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Société Mixte Immobilière de Rambouillet (SEMIR)
43,003d5e30-d8be-49de-a8ca-de718750a615,d28139,membre,Brut,NaN,true,01/2011,11/2017,CREATION,NaN,Société des Courses de Rambouillet
44,003d5e30-d8be-49de-a8ca-de718750a615,d28140,Membre,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Maison de l'emploi Centre et Sud Yvelines
45,003d5e30-d8be-49de-a8ca-de718750a615,d28141,Membre,Brut,NaN,false,01/2011,04/2014,CREATION,NaN,Conseil d'administration du Centre d'enseignem...
46,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2335,Président,Brut,Société dissoute en 2015 et transformée en soc...,NaN,01/2013,03/2015,CREATION,NaN,Société d'aménagement d'économie mixte Val de ...
47,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2336,Administrateur,Net,NaN,NaN,03/2015,NaN,CREATION,NaN,Société publique locale Val de Seine Aménagement
48,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2337,Membre du conseil de surveillance,Net,NaN,NaN,01/2013,NaN,CREATION,NaN,AP-HP
49,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2338,Président,Net,NaN,NaN,01/2013,NaN,CREATION,NaN,Conseil de surveillance du groupe HUPIFO de l'...
50,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2339,Président,Net,NaN,NaN,01/2013,NaN,CREATION,NaN,Centre de Gérontologie des Abondances
51,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2340,Président,Net,NaN,NaN,01/2013,NaN,CREATION,NaN,Centre communal d'Action sociale de Boulogne-B...
52,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2341,Membre du conseil de surveillance,Net,NaN,NaN,06/2017,NaN,CREATION,NaN,Agence régionale de santé d'Ile de France
53,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2342,Délégué,Net,NaN,NaN,01/2014,NaN,CREATION,NaN,SYCTOM
54,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2343,Conseiller métropolitain,Net,NaN,NaN,01/2018,NaN,CREATION,NaN,Métropole du Grand Paris
55,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2344,Vice-Président,Net,NaN,NaN,07/2020,NaN,CREATION,NaN,Association des maires des Hauts de Seine
56,0047f75f-2f4d-47e1-be14-e3592ae5cfbe,d2345,membre du conseil d'administration,Net,NaN,NaN,06/2014,NaN,CREATION,NaN,Société publique locale Seine Ouest Aménagement
57,00530729-fb5c-432b-9773-9458032b7007,d38330,Membre du CA,Net,NaN,false,01/2011,10/2017,CREATION,NaN,Association archéologique
58,00530729-fb5c-432b-9773-9458032b7007,d38331,Membre du CA,Net,NaN,false,01/2011,12/2016,CREATION,NaN,Association historique
59,00530729-fb5c-432b-9773-9458032b7007,d38332,Membre du CA,Net,Représentant du Conseil départemental des Haut...,true,03/2015,12/2017,CREATION,NaN,Collège É. Galois de Bourg-la-Reine
60,00619b4e-7482-49ce-9e63-5e4f980b9a86,d22043,administrateur,Brut,NaN,NaN,01/2013,08/2019,CREATION,NaN,Collège Vauban Belfort
61,00619b4e-7482-49ce-9e63-5e4f980b9a86,d22044,administrateur,Brut,NaN,NaN,01/2016,08/2019,CREATION,NaN,Lycée Follereau Belfort
62,00619b4e-7482-49ce-9e63-5e4f980b9a86,d22045,administrateur,Brut,NaN,NaN,01/2013,08/2019,CREATION,NaN,OGEC Institution Sainte-Marie Belfort
63,00619b4e-7482-49ce-9e63-5e4f980b9a86,d22046,Président,Brut,NaN,NaN,01/2013,08/2019,CREATION,NaN,MOUVEMENT DEMOCRATE DU TERRITOIRE DE BELFORT
64,00619b4e-7482-49ce-9e63-5e4f980b9a86,d22047,Membre,Brut,NaN,NaN,06/2016,08/2019,CREATION,NaN,BUREAU EXECUTIF NATIONAL MOUVEMENT DEMOCRATE
65,00619b4e-7482-49ce-9e63-5e4f980b9a86,d22048,administrateur,Brut,NaN,NaN,01/2013,08/2019,CREATION,NaN,SDIS TERRITOIRE DE BELFORT
66,00619b4e-7482-49ce-9e63-5e4f980b9a86,d22049,administrateur,Brut,NaN,NaN,01/2014,08/2019,CREATION,NaN,CENTRE DE GESTION DE LA FONCTION PUBLIQUE TERR...
67,0067f38c-d05b-4649-ae0a-62484ed1a376,d21042,Président,Net,Indemnités brutes (et non pas nettes). Préside...,NaN,10/2017,NaN,CREATION,NaN,SDIS de la Gironde
68,0067f38c-d05b-4649-ae0a-62484ed1a376,d21043,Président,Net,Présidence depuis le 24 Mai 2017,NaN,05/2017,NaN,CREATION,NaN,Gironde Ressources
69,0067f38c-d05b-4649-ae0a-62484ed1a376,d21044,Président,Net,Fin de présidence le 18 Juillet 2018,NaN,04/2015,07/2018,CREATION,NaN,SEM Route des Lasers
70,0067f38c-d05b-4649-ae0a-62484ed1a376,d21045,Président,Net,SEM liquidée en Novembre 2021. La période de p...,NaN,04/2015,11/2021,CREATION,NaN,SEM Gironde Développement
71,0067f38c-d05b-4649-ae0a-62484ed1a376,d21046,"Vice-Président, puis membre délégué à compter ...",Net,Indemnités brutes (et non pas nettes). Vice-Pr...,NaN,04/2015,10/2020,CREATION,NaN,Syndicat mixte de gestion et d'aménagement du ...
72,0067f38c-d05b-4649-ae0a-62484ed1a376,d21047,Membre du Conseil d'Administration,Net,NaN,NaN,04/2015,NaN,CREATION,NaN,EHPAD Hubert Lalanne à Préchac
73,0067f38c-d05b-4649-ae0a-62484ed1a376,d21048,Membre du Conseil de surveillance,Net,NaN,NaN,07/2021,NaN,CREATION,NaN,Centre hospitalier de Bazas
74,0067f38c-d05b-4649-ae0a-62484ed1a376,d21049,Membre du Conseil de surveillance,Net,NaN,NaN,07/2021,NaN,CREATION,NaN,Centre hospitalier Sud Gironde
75,0067f38c-d05b-4649-ae0a-62484ed1a376,d21050,Membre,Net,NaN,NaN,04/2015,NaN,CREATION,NaN,Association Excellence Bazadaise
76,0067f38c-d05b-4649-ae0a-62484ed1a376,d21051,Membre du Conseil d'administration,Net,NaN,NaN,04/2015,09/2019,CREATION,NaN,SPL Sud Gironde
77,0067f38c-d05b-4649-ae0a-62484ed1a376,d21052,Membre du Conseil d'Administration,Net,NaN,NaN,04/2015,NaN,CREATION,NaN,Collège Ausone Bazas
78,0067f38c-d05b-4649-ae0a-62484ed1a376,d21053,Membre du Conseil d'Administration,Net,NaN,NaN,04/2015,NaN,CREATION,NaN,Collège Toulouse Lautrec à Langon
79,0067f38c-d05b-4649-ae0a-62484ed1a376,d21054,Membre du Conseil d'Administration,Net,NaN,NaN,04/2015,NaN,CREATION,NaN,Collège Jules Ferry à Langon
80,00699e42-9ccb-4380-afcc-d75e9934b394,d20619,Président,Net,NaN,NaN,01/2016,06/2021,CREATION,NaN,SPL
81,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18907,président,Net,NaN,NaN,01/2015,10/2021,CREATION,NaN,Société SEM Gaz et Electricité de Grenoble
82,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18908,président du conseil de surveillance,Net,La SAS GreenAlp est la filiale de la SEM GEG c...,NaN,06/2018,10/2021,CREATION,NaN,société SAS GreenAlp
83,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18909,membre du conseil d'administration,Net,Je suis administrateur au titre de la Ville de...,NaN,06/2017,07/2020,CREATION,NaN,SAEML Grenoble Habitat
84,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18910,membre du conseil d'administration,Net,Mandat d'administrateur au titre de la Ville d...,NaN,01/2015,10/2021,CREATION,NaN,SEM Innovia
85,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18911,membre du conseil d'administration,Net,Je suis administrateur au titre de la Ville de...,NaN,01/2015,07/2020,CREATION,NaN,SPL SAGES
86,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18912,membre du conseil d'administration,Net,Mandat d'administrateur au titre de la Ville d...,NaN,01/2015,10/2021,CREATION,NaN,SEM CCIAG Compagnie Chauffage
87,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18913,membre du conseil d'administration,Net,administrateur au titre de la Ville de Grenobl...,NaN,01/2015,07/2020,CREATION,NaN,SEM Territoire 38
88,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18914,membre du conseil d'administration,Net,Mandat d'administrateur au titre de la Ville d...,NaN,02/2020,10/2021,CREATION,NaN,SPL ALEC
89,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18915,trésorier,Net,NaN,NaN,01/2015,09/2020,CREATION,NaN,Agence d'Urbanisme de la Région Grenobloise As...
90,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18916,membre du conseil d'administration,Net,NaN,NaN,01/2015,09/2020,CREATION,NaN,Etablissement Public Foncier Local du Dauphiné
91,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18917,Membre du CA représantant de l'assemblée spéciale,Net,Membre du CA au titre des fonctions de Préside...,NaN,03/2018,10/2021,CREATION,NaN,SPL OSER d'efficacité énergétique
92,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18918,membre du CA,Net,Représentant la Ville de Grenoble,NaN,04/2015,07/2017,CREATION,NaN,OPH ACTIS
93,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18919,membre du conseil d'exploitation,Net,nommé par délibération du conseil municipal,NaN,06/2015,10/2021,CREATION,NaN,Régie Lumière Grenoble lumière
94,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18920,"Comité Syndical, délégué suppléant",Net,représentant de la Métropole de Grenoble GAM,NaN,10/2020,10/2021,CREATION,NaN,Syndicat Mixte des bassins hydrauliques de l'I...
95,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18921,"comité syndical, membre titulaire, membre du b...",Net,représentant de Grenoble Alpes Métropole,NaN,10/2020,10/2021,CREATION,NaN,EP SCOT de la grande région grenobloise
96,0077f258-22a6-473d-bffe-e13f8ee5b6cd,d18922,membre du CA,Net,au titre de mon mandat de Président de la SEM ...,NaN,01/2015,10/2021,CREATION,NaN,Fédération Nationale des Collectivités Concéda...
97,007be442-7dc6-4628-acec-b384d03030ad,d43428,membre du conseil d'administration,Net,en tant que maire et président d'agglomération...,false,03/2014,12/2015,CREATION,NaN,LRA
98,007be442-7dc6-4628-acec-b384d03030ad,d43429,Membre du conseil d'administration,Net,NaN,false,03/2014,08/2017,CREATION,NaN,SEGARD
99,007e3535-60b1-410b-9c35-68ebdacf610a,d1536,PDG,Net,NaN,NaN,03/2020,NaN,CREATION,NaN,SEML Eaux de Mouans

In [ ]:
# encodage id_declaration
participationDirigeantDto['id_declaration'] = encoder_id_declaration.transform(participationDirigeantDto['id_declaration'])

In [378]:
# export en csv
participationDirigeantDto.to_csv(folder_export + 'participationDirigeantDto.csv', index=False)

In [401]:
participationDirigeantDto.shape

(52220, 11)

## Table Ressources 2

In [404]:
# conditions de mapping entre le chemin xml et les champs de la table en cours
mask_champs_ressources = (data3['chemins'].str.contains('participationDirigeantDto/items/', na=False))

champs_ressources2 = data3[mask_champs_ressources]['chemins'].unique()
champs_ressources2

array(['participationDirigeantDto/items/items/motif/id',
       'participationDirigeantDto/items/items/commentaire',
       'participationDirigeantDto/items/items/nomSociete',
       'participationDirigeantDto/items/items/activite',
       'participationDirigeantDto/items/items/remuneration/brutNet',
       'participationDirigeantDto/items/items/remuneration/montant/montant/annee',
       'participationDirigeantDto/items/items/remuneration/montant/montant/montant',
       'participationDirigeantDto/items/items/dateDebut',
       'participationDirigeantDto/items/items/dateFin',
       'participationDirigeantDto/items/items/conservee',
       'participationDirigeantDto/items/items/motif/label'], dtype=object)

In [405]:
# creation de la table
ressources2 = data3[data3['chemins'].isin(champs_ressources2)][['id_declaration', 'champs', 'valeurs']]
ressources2.head(20)

,id_declaration,champs,valeurs
151,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
152,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Président du SDIS 01. Activité arrêtée depuis ...
153,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,SDIS 01
154,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Service départemental d'incendie et de secours
156,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Brut
159,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2015
160,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
162,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2016
163,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
165,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017
166,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0
167,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,04/2015
168,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,07/2017
171,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION
172,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Président de l'association AINTOURISME qui dév...
173,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,ASSOCIATION AINTOURISME
174,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Président d'Aintourisme qui a pour objet la po...
176,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net
179,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017
180,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0

In [406]:
ressources2.shape

(731111, 3)

In [396]:
# ajout de l'id_dirigeant
ids_part_dir2 = []
champs_part_dir2 = []

# creation de l'id_dirigeant, qui s'incrémente à chaque nouvelle activité, chaque nouveau id dans le tableau
for element in tqdm(ressources2['champs'].values):
    champs_part_dir2.append(element)
    i = f'd{champs_part_dir2.count("id") - 1}'
    ids_part_dir2.append(i)

100%|█████████████████████████████████████████████████████████████████████████| 731111/731111 [57:18<00:00, 212.62it/s]

In [403]:
len(ids_part_dir2)

731111

In [407]:
# creation de la colonne id_activité dans ressources, en tant que clé étrangère
ressources2['id_activite'] = ids_part_dir2
ressources2.head(20)

,id_declaration,champs,valeurs,id_activite
151,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,d0
152,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Président du SDIS 01. Activité arrêtée depuis ...,d0
153,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,SDIS 01,d0
154,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Service départemental d'incendie et de secours,d0
156,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Brut,d0
159,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2015,d0
160,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,d0
162,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2016,d0
163,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,d0
165,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,d0
166,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,d0
167,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDebut,04/2015,d0
168,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateFin,07/2017,d0
171,4344aaa1-874d-4e6d-9b1a-45f7725b710c,id,CREATION,d1
172,4344aaa1-874d-4e6d-9b1a-45f7725b710c,commentaire,Président de l'association AINTOURISME qui dév...,d1
173,4344aaa1-874d-4e6d-9b1a-45f7725b710c,nomSociete,ASSOCIATION AINTOURISME,d1
174,4344aaa1-874d-4e6d-9b1a-45f7725b710c,activite,Président d'Aintourisme qui a pour objet la po...,d1
176,4344aaa1-874d-4e6d-9b1a-45f7725b710c,brutNet,Net,d1
179,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,d1
180,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,d1

In [ ]:
# suppression des colonnes qui ne sont pas des ressources
ressources2 = ressources2[ressources2['champs'].isin(['annee', 'montant'])]
ressources2.head()

In [410]:
# ajout de l'id_ressources
ids_ressources2 = []
champs_ressources2 = []


# creation de l'id_ressources, qui s'incrémente à chaque nouvelle année
for element in tqdm(ressources2['champs'].values):
    champs_ressources2.append(element)
    i = ressources['id_ressource'].max() + champs_ressources2.count("annee")
    ids_ressources2.append(i)

100%|█████████████████████████████████████████████████████████████████████████| 413313/413313 [21:30<00:00, 320.22it/s]

In [411]:
# creation de la colonne id_ressources dans ressources, en tant que clé primaire
ressources2['id_ressource'] = ids_ressources2
ressources2.head()

,id_declaration,champs,valeurs,id_activite,id_ressource
159,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2015,d0,118181
160,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,d0,118181
162,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2016,d0,118182
163,4344aaa1-874d-4e6d-9b1a-45f7725b710c,montant,0,d0,118182
165,4344aaa1-874d-4e6d-9b1a-45f7725b710c,annee,2017,d0,118183

In [ ]:
# suppression des doublons
ressources2 = ressources2.drop(ressources2[ressources2.duplicated(subset=['id_declaration',
                                                         'champs', 'id_activite', 'id_ressource'], keep=False)].index)

In [ ]:
# pivot de la table ressources
ressources2 = ressources2.pivot(index=['id_declaration', 'id_activite', 'id_ressource'],
                                          columns='champs', values='valeurs').reset_index()
ressources2.head()

In [414]:
# encodage id_declaration
ressources2['id_declaration'] = encoder_id_declaration.transform(ressources2['id_declaration'])

# export en csv
ressources2.to_csv(folder_export + 'ressources2.csv', index=False)

In [425]:
pd.read_csv(folder_export + 'ressources2.csv')

        id_declaration id_activite  id_ressource  annee montant
0                    2      d39447        273362   2012       0
1                    2      d39447        273363   2013       0
2                    2      d39447        273364   2014       0
3                    2      d39447        273365   2015       0
4                    2      d39447        273366   2016       0
...                ...         ...           ...    ...     ...
206685           10871       d5728        140895   2018       0
206686           10871       d5728        140896   2019       0
206687           10873      d35011        256204   2017       0
206688           10873      d35011        256205   2018       0
206689           10873      d35011        256206   2019       0

[206690 rows x 5 columns]

## activConsultantDto

In [30]:
pd.read_csv(folder_export + 'data_nettoyees.csv')

,id_declaration,chemins,champs,valeurs
0,4344aaa1-874d-4e6d-9b1a-45f7725b710c,dateDepot,dateDepot,11/07/2022 15:40:13
1,4344aaa1-874d-4e6d-9b1a-45f7725b710c,uuid,uuid,4344aaa1-874d-4e6d-9b1a-45f7725b710c
2,4344aaa1-874d-4e6d-9b1a-45f7725b710c,origine,origine,ADEL
3,4344aaa1-874d-4e6d-9b1a-45f7725b710c,complete,complete,true
4,4344aaa1-874d-4e6d-9b1a-45f7725b710c,attachedFiles/attachedFiles/fileName,fileName,VUE_PDF_DU_RECEPISSE_DU_DEPOT_XML
...,...,...,...,...
1944203,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/voie,voie,[Données non publiées]
1944204,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/complement,complement,[Données non publiées]
1944205,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/codePostal,codePostal,[Données non publiées]
1944206,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/ville,ville,[Données non publiées]
1944207,d1129c22-a715-4df6-8c0f-cfc678f1518c,general/declarant/adresseDec/pays,pays,[Données non publiées]

In [32]:
id_declarations = pd.read_csv(folder_export + 'data_nettoyees.csv')['id_declaration'].unique()

encoder_id_declaration = LabelEncoder()

encoder_id_declaration.fit(id_declarations)

LabelEncoder()

In [33]:
def creation_table(chemins, champs_levier):

    # chemins de la table
    mask_champs_table = (data3['chemins'].str.contains(chemins, na=False)) & ~(data3['chemins'].str.contains('montant/', na=False))
    
    # champs associés au chemin
    champs_table = data3[mask_champs_table]['chemins'].unique()
    
    # creation de la table
    table = data3[data3['chemins'].isin(champs_table)][['id_declaration', 'champs', 'valeurs']]
    print(f"Table {chemins.replace('/items/', '')} créée")
    
    # encodage id_declaration
    table['id_declaration'] = encoder_id_declaration.transform(table['id_declaration'])
    

    # créer l'id de la table, qui s'incremente par rapport à un champs levier
    table = id_table(nom_table=table, champs_levier=champs_levier)
    
    
    # supression des doublons
    table = table.drop(table[table.duplicated(subset=['id_declaration','champs', 'id_table'], keep='last')].index)

    # pivot table
    table = table.pivot(index=['id_declaration', 'id_table'], columns='champs', values='valeurs').reset_index()
    
    # renommage id_table
    table = table.rename(columns={'id_table': f"id_{chemins.replace('/items/', '')}"})
    
    print(f"Table {chemins.replace('/items/', '')} créée, avec {table.shape[0]} lignes et {table.shape[1]} colonnes.")
    print(f"Les colonnes : {table.columns}")    
    nom_tableau = chemins.replace('/items/', '')
    
    # export en csv
    table.to_csv(folder_export + f'{nom_tableau}.csv', index=False)
    print('Fichier exporté')
    
    return table

In [42]:
def creation_table_parente_avec_ressources(chemins, lettre_id_table_mere):

    # chemins de la table
    mask_champs_table = (data3['chemins'].str.contains(chemins, na=False)) & ~(data3['chemins'].str.contains('montant/', na=False))
    
    # champs associés au chemin
    champs_table = data3[mask_champs_table]['chemins'].unique()
    
    # creation de la table
    table = data3[data3['chemins'].isin(champs_table)][['id_declaration', 'champs', 'valeurs']]
    print(f"Table {chemins.replace('/items/', '')} créée")
    
    # encodage id_declaration
    table['id_declaration'] = encoder_id_declaration.transform(table['id_declaration'])
    

    # créer l'id de la table, qui s'incremente par rapport à un champs levier
    table = id_table2(nom_table=table, lettre_id_table_mere=lettre_id_table_mere)
    
    
    # supression des doublons
    table = table.drop(table[table.duplicated(subset=['id_declaration','champs', 'id_table'], keep='last')].index)

    # pivot table
    table = table.pivot(index=['id_declaration', 'id_table'], columns='champs', values='valeurs').reset_index()
    
    # renommage id_table
    table = table.rename(columns={'id_table': f"id_{chemins.replace('/items/', '')}"})
    
    print(f"Table {chemins.replace('/items/', '')} créée, avec {table.shape[0]} lignes et {table.shape[1]} colonnes.")
    print(f"Les colonnes : {table.columns}")    
    nom_tableau = chemins.replace('/items/', '')
    
    # export en csv
    table.to_csv(folder_export + f'{nom_tableau}.csv', index=False)
    print('Fichier exporté')
    
    return table

In [35]:
def id_table(nom_table, champs_levier):

    # ajout de l'id de la table
    ids_table = []
    champs_table = []

    # creation de l'id de la table, qui s'incrémente à chaque nouvel élément, c'est à dire à chaque 'champs_repere_nouvelle_ligne'
    for element in tqdm(nom_table['champs'].values):
        champs_table.append(element)
        i = champs_table.count(champs_levier) - 1
        ids_table.append(i)

    nom_table['id_table'] = ids_table

    return nom_table

In [41]:
def id_table2(nom_table, lettre_id_table_mere):

    # ajout de l'id de la table
    ids_table = []
    champs_table = []

    # creation de l'id de la table, qui s'incrémente à chaque nouvel élément, c'est à dire à chaque 'champs_repere_nouvelle_ligne'
    for element in tqdm(nom_table['champs'].values):
        champs_table.append(element)
        i = f'{lettre_id_table_mere}{champs_table.count("id") - 1}'
        ids_table.append(i)

    nom_table[f'id_table'] = ids_table

    return nom_table

In [43]:
activConsultantDto = creation_table_parente_avec_ressources(chemins='activConsultantDto/items/', lettre_id_table_mere='c')

Table activConsultantDto créée

100%|███████████████████████████████████████████████████████████████████████████| 9038/9038 [00:00<00:00, 17412.83it/s]

Table activConsultantDto créée, avec 1375 lignes et 11 colonnes.
Les colonnes : Index(['id_declaration', 'id_activConsultantDto', 'brutNet', 'commentaire',
       'conservee', 'dateDebut', 'dateFin', 'description', 'id', 'label',
       'nomEmployeur'],
      dtype='object', name='champs')
Fichier exporté

## activProfCinqDerniereDto

In [44]:
activProfCinqDerniereDto = creation_table_parente_avec_ressources(chemins='activProfCinqDerniereDto/items/', lettre_id_table_mere='p')

Table activProfCinqDerniereDto créée

100%|██████████████████████████████████████████████████████████████████████████| 87899/87899 [00:48<00:00, 1806.69it/s]

Table activProfCinqDerniereDto créée, avec 13452 lignes et 11 colonnes.
Les colonnes : Index(['id_declaration', 'id_activProfCinqDerniereDto', 'brutNet',
       'commentaire', 'conservee', 'dateDebut', 'dateFin', 'description',
       'employeur', 'id', 'label'],
      dtype='object', name='champs')
Fichier exporté

In [79]:
activProfCinqDerniereDto.head(100)

,id_declaration,champs,valeurs
378,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,id,CREATION
379,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,commentaire,Fonction exercée du 20 Mai au 4 Juillet 2022 ...
380,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,description,"Ministre des Solidarités, de l'Autonomie et de..."
381,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,employeur,"MINISTERE DES SOLIDARITES, DE L'AUTONOMIE ET D..."
383,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,brutNet,Net
388,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,dateDebut,05/2022
389,fa8d18ec-0db9-4a39-b1f4-caba0c31329b,dateFin,07/2022
762,21916899-a643-428c-824e-3aedf9ee103e,id,CREATION
763,21916899-a643-428c-824e-3aedf9ee103e,conservee,false
764,21916899-a643-428c-824e-3aedf9ee103e,description,CHEF DE PROJET WEB
765,21916899-a643-428c-824e-3aedf9ee103e,employeur,AKTOR INTERACTIVE
767,21916899-a643-428c-824e-3aedf9ee103e,brutNet,Net
775,21916899-a643-428c-824e-3aedf9ee103e,dateDebut,01/2014
776,21916899-a643-428c-824e-3aedf9ee103e,dateFin,03/2015
779,21916899-a643-428c-824e-3aedf9ee103e,id,CREATION
780,21916899-a643-428c-824e-3aedf9ee103e,conservee,true
781,21916899-a643-428c-824e-3aedf9ee103e,description,PRESIDENTE
782,21916899-a643-428c-824e-3aedf9ee103e,employeur,DGDC
784,21916899-a643-428c-824e-3aedf9ee103e,brutNet,Net
810,21916899-a643-428c-824e-3aedf9ee103e,dateDebut,11/2015
1185,ac693815-1521-4a79-a314-6bd830de8988,id,CREATION
1186,ac693815-1521-4a79-a314-6bd830de8988,description,Responsable unité
1187,ac693815-1521-4a79-a314-6bd830de8988,employeur,Région Occitanie
1189,ac693815-1521-4a79-a314-6bd830de8988,brutNet,Net
1203,ac693815-1521-4a79-a314-6bd830de8988,dateDebut,07/2018
1204,ac693815-1521-4a79-a314-6bd830de8988,dateFin,07/2021
1207,ac693815-1521-4a79-a314-6bd830de8988,id,CREATION
1208,ac693815-1521-4a79-a314-6bd830de8988,description,Directrice adjointe
1209,ac693815-1521-4a79-a314-6bd830de8988,employeur,La Pradette Billières
1211,ac693815-1521-4a79-a314-6bd830de8988,brutNet,Net
1216,ac693815-1521-4a79-a314-6bd830de8988,dateDebut,01/2017
1217,ac693815-1521-4a79-a314-6bd830de8988,dateFin,12/2017
1337,61853e75-80cc-457b-865c-80456d4a0985,id,CREATION
1338,61853e75-80cc-457b-865c-80456d4a0985,description,comptable
1339,61853e75-80cc-457b-865c-80456d4a0985,employeur,SARL ABAUX
1341,61853e75-80cc-457b-865c-80456d4a0985,brutNet,Net
1349,61853e75-80cc-457b-865c-80456d4a0985,dateDebut,01/2015
1350,61853e75-80cc-457b-865c-80456d4a0985,dateFin,09/2016
1894,2b6da666-15d3-4864-9231-7a7dd5ae9dda,id,CREATION
1895,2b6da666-15d3-4864-9231-7a7dd5ae9dda,description,Attachée culturelle à New York
1896,2b6da666-15d3-4864-9231-7a7dd5ae9dda,employeur,Ministère des Affaires Etrangères
1898,2b6da666-15d3-4864-9231-7a7dd5ae9dda,brutNet,Net
1915,2b6da666-15d3-4864-9231-7a7dd5ae9dda,dateDebut,09/2014
1916,2b6da666-15d3-4864-9231-7a7dd5ae9dda,dateFin,08/2018
1919,2b6da666-15d3-4864-9231-7a7dd5ae9dda,id,CREATION
1920,2b6da666-15d3-4864-9231-7a7dd5ae9dda,description,Conseillère Culture
1921,2b6da666-15d3-4864-9231-7a7dd5ae9dda,employeur,Présidence de la République
1923,2b6da666-15d3-4864-9231-7a7dd5ae9dda,brutNet,Net
1937,2b6da666-15d3-4864-9231-7a7dd5ae9dda,dateDebut,11/2019
1938,2b6da666-15d3-4864-9231-7a7dd5ae9dda,dateFin,05/2022
2342,3e209d45-8656-45ac-a8c8-451542abe786,id,CREATION
2343,3e209d45-8656-45ac-a8c8-451542abe786,commentaire,demande de détachement à compter du 2/09/2021
2344,3e209d45-8656-45ac-a8c8-451542abe786,description,chargée de ressources humaines dans un syndica...
2345,3e209d45-8656-45ac-a8c8-451542abe786,employeur,SOLURIS
2347,3e209d45-8656-45ac-a8c8-451542abe786,brutNet,Net
2358,3e209d45-8656-45ac-a8c8-451542abe786,dateDebut,08/2019
2359,3e209d45-8656-45ac-a8c8-451542abe786,dateFin,09/2021
2362,3e209d45-8656-45ac-a8c8-451542abe786,id,CREATION
2363,3e209d45-8656-45ac-a8c8-451542abe786,description,chargée de mission emploi
2364,3e209d45-8656-45ac-a8c8-451542abe786,employeur,Département de la Vienne
2366,3e209d45-8656-45ac-a8c8-451542abe786,brutNet,Net
2380,3e209d45-8656-45ac-a8c8-451542abe786,dateDebut,07/2016
2381,3e209d45-8656-45ac-a8c8-451542abe786,dateFin,08/2019
2638,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,id,CREATION
2639,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,commentaire,Pas d'activité professionnelle
2640,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,description,0
2641,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,employeur,0
2643,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,brutNet,Net
2666,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,dateDebut,01/2014
2667,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,dateFin,10/2020
2956,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,id,CREATION
2957,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,commentaire,Pas d'activité professionnelle
2958,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,description,0
2959,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,employeur,0
2961,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,brutNet,Net
2984,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,dateDebut,01/2014
2985,a1a11106-bfe2-40a4-89dc-71ae7adfd7fa,dateFin,10/2020
3274,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,id,CREATION
3275,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,commentaire,Pas d'activité professionnelle et aucune rémun...
3276,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,description,administrateur de l'office culturel du pays Ch...
3277,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,employeur,président de l'agglomération Grand Chatellerault
3279,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,brutNet,Net
3302,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,dateDebut,01/2015
3303,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,dateFin,04/2021
3306,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,id,CREATION
3307,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,commentaire,pas d'activité professionnelle et aucune rémun...
3308,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,description,administrateur de la société d'équipement du p...
3309,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,employeur,Grand Chatellerault
3311,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,brutNet,Net
3334,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,dateDebut,01/2015
3335,900e1c2b-91a1-487a-9d03-fbe1ae6831bf,dateFin,04/2021
3587,76933453-9495-40e7-8c1a-e5676dd82004,id,CREATION
3588,76933453-9495-40e7-8c1a-e5676dd82004,description,Fonctionnaire
3589,76933453-9495-40e7-8c1a-e5676dd82004,employeur,Conseil Régional 971
3591,76933453-9495-40e7-8c1a-e5676dd82004,brutNet,Net
3611,76933453-9495-40e7-8c1a-e5676dd82004,dateDebut,01/2015
3612,76933453-9495-40e7-8c1a-e5676dd82004,dateFin,06/2020
3723,b0268727-af55-4a2a-98fb-6bf6b88cd82b,id,CREATION
3724,b0268727-af55-4a2a-98fb-6bf6b88cd82b,description,Fonctionnaire
3725,b0268727-af55-4a2a-98fb-6bf6b88cd82b,employeur,Conseil Régional 971

## assuranceVieDto

In [96]:
assuranceVieDto = creation_table(chemins='assuranceVieDto/items/', champs_levier='id')

Table assuranceVieDto créée

100%|██████████████████████████████████████████████████████████████████████████| 1318/1318 [00:00<00:00, 109900.25it/s]

Table assuranceVieDto créée, avec 199 lignes et 11 colonnes.
Les colonnes : Index(['id_declaration', 'idassuranceVieDto', 'commentaire', 'conservee',
       'dateSouscription', 'etablissement', 'id', 'label', 'reference',
       'souscripteur', 'valeurRachat'],
      dtype='object', name='champs')
Fichier exporté

In [97]:
assuranceVieDto.head()

champs,id_declaration,idassuranceVieDto,commentaire,conservee,dateSouscription,etablissement,id,label,reference,souscripteur,valeurRachat
0,251,60,[Données non publiées],NaN,30/11/2020,AGEAS,CREATION,NaN,[Données non publiées],Dujols Dominique,31202
1,251,61,[Données non publiées],NaN,30/09/2015,CEIDF,CREATION,NaN,[Données non publiées],Dominique DUJOLS,64825
2,433,18,Valeur de rachat au 30 juin 2022.,false,02/12/1999,Axa,CREATION,NaN,[Données non publiées],Jean-Noël Barrot,3939
3,433,19,Valeur de rachat au 01/08/2022,NaN,07/03/2018,Crédit Agricole,CREATION,NaN,[Données non publiées],Jean-Noël Barrot,1570156
4,499,178,NaN,false,24/06/2011,BNP [Données non publiées],CREATION,Entrée dans le patrimoine,[Données non publiées],Provost-Lopin Martine,188612

## autreBienDto

In [100]:
autreBienDto = creation_table(chemins='autreBienDto/items/', champs_levier='id')

Table autreBienDto créée

100%|████████████████████████████████████████████████████████████████████████████| 242/242 [00:00<00:00, 242017.54it/s]

Table autreBienDto créée, avec 55 lignes et 8 colonnes.
Les colonnes : Index(['id_declaration', 'idautreBienDto', 'commentaire', 'conservee',
       'denomination', 'description', 'id', 'valeur'],
      dtype='object', name='champs')
Fichier exporté

In [101]:
autreBienDto.head()

champs,id_declaration,idautreBienDto,commentaire,conservee,denomination,description,id,valeur
0,433,4,Compte courant d'associés d'une valeur au 31/1...,false,SCI [Données non publiées],Compte courant d'associés,CREATION,126567
1,433,5,39.501 : Compte courant d'associé en pleine pr...,NaN,SCI [Données non publiées],Compte courant d'associé,CREATION,45181
2,433,6,Indivision [Données non publiées] Qu...,NaN,Caisse des Règlements Pécuniaires des Avocats ...,Liquidités,CREATION,313573
3,499,45,NaN,NaN,NaN,créances de restitution de deux contrats d'ass...,CREATION,118186
4,594,42,[Données non publiées],NaN,NaN,Prêt [Données non publiées],CREATION,300000

## bienDiverDto

In [102]:
bienDiverDto = creation_table(chemins='bienDiverDto/items/', champs_levier='id')

bienDiverDto.head()

Table bienDiverDto créée

100%|██████████████████████████████████████████████████████████████████████████████████████████| 63/63 [00:00<?, ?it/s]

Table bienDiverDto créée, avec 13 lignes et 8 colonnes.
Les colonnes : Index(['id_declaration', 'idbienDiverDto', 'commentaire', 'conservee',
       'description', 'id', 'typeEstimation', 'valeur'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idbienDiverDto,commentaire,conservee,description,id,typeEstimation,valeur
0,267,8,NaN,false,Lithographies et tableaux,CREATION,Évaluation personnelle,15000
1,267,9,[Données non publiées],false,Mobilier - Commode,CREATION,Évaluation personnelle,10000
2,4011,7,Achat mobilier qui ne sera effectif que le 20....,NaN,Un APPARTEMENT au cinquième étage gauche ...,CREATION,Valeur d’acquisition,2390000
3,4618,11,[Données non publiées],NaN,Tableau [Données non publiées],CREATION,demande à expert octobre 2018,30000
4,6787,1,NaN,NaN,Montre : ROLEX Daytona,CREATION,Expertise,13000

In [103]:
    # chemins de la table
mask_champs_table = (data3['chemins'].str.contains('bienDiverDto/items/', na=False)) & ~(data3['chemins'].str.contains('montant/', na=False))
    
    # champs associés au chemin
champs_table = data3[mask_champs_table]['chemins'].unique()
    
    # creation de la table
table = data3[data3['chemins'].isin(champs_table)][['id_declaration', 'champs', 'valeurs']]

table

,id_declaration,champs,valeurs
2102,d18ae83a-4925-4b45-ba5d-3ee5b9090fc3,id,CREATION
2103,d18ae83a-4925-4b45-ba5d-3ee5b9090fc3,commentaire,valeur d'acquisition = 280.000 euros
2104,d18ae83a-4925-4b45-ba5d-3ee5b9090fc3,description,Appartement 2 pièces 41m2
2105,d18ae83a-4925-4b45-ba5d-3ee5b9090fc3,valeur,330000
2106,d18ae83a-4925-4b45-ba5d-3ee5b9090fc3,typeEstimation,Évaluation personnelle
987593,a076c00d-7883-479c-9085-af970be7c7e9,id,CREATION
987594,a076c00d-7883-479c-9085-af970be7c7e9,description,Montre : ROLEX Daytona
987595,a076c00d-7883-479c-9085-af970be7c7e9,valeur,13000
987596,a076c00d-7883-479c-9085-af970be7c7e9,typeEstimation,Expertise
987599,a076c00d-7883-479c-9085-af970be7c7e9,id,CREATION
987600,a076c00d-7883-479c-9085-af970be7c7e9,description,Montre : JOURNE Chronomètre souverain
987601,a076c00d-7883-479c-9085-af970be7c7e9,valeur,25000
987602,a076c00d-7883-479c-9085-af970be7c7e9,typeEstimation,Expertise
1089183,a7f9de1e-809e-4702-b1c2-57bccdff4579,id,CREATION
1089184,a7f9de1e-809e-4702-b1c2-57bccdff4579,conservee,false
1089185,a7f9de1e-809e-4702-b1c2-57bccdff4579,description,TABLEAU [Données non publiées]
1089186,a7f9de1e-809e-4702-b1c2-57bccdff4579,valeur,11000
1089187,a7f9de1e-809e-4702-b1c2-57bccdff4579,typeEstimation,Valeur d’acquisition
1089190,a7f9de1e-809e-4702-b1c2-57bccdff4579,id,CREATION
1089191,a7f9de1e-809e-4702-b1c2-57bccdff4579,conservee,false
1089192,a7f9de1e-809e-4702-b1c2-57bccdff4579,description,TABLEAU [Données non publiées]
1089193,a7f9de1e-809e-4702-b1c2-57bccdff4579,valeur,13000
1089194,a7f9de1e-809e-4702-b1c2-57bccdff4579,typeEstimation,Valeur d’acquisition
1089748,a2877b74-05a6-445d-9774-f701e2dd922a,id,CREATION
1089749,a2877b74-05a6-445d-9774-f701e2dd922a,conservee,false
1089750,a2877b74-05a6-445d-9774-f701e2dd922a,description,TABLEAU [Données non publiées]
1089751,a2877b74-05a6-445d-9774-f701e2dd922a,valeur,11000
1089752,a2877b74-05a6-445d-9774-f701e2dd922a,typeEstimation,Valeur d’acquisition
1089755,a2877b74-05a6-445d-9774-f701e2dd922a,id,CREATION
1089756,a2877b74-05a6-445d-9774-f701e2dd922a,conservee,false
1089757,a2877b74-05a6-445d-9774-f701e2dd922a,description,TABLEAU [Données non publiées]
1089758,a2877b74-05a6-445d-9774-f701e2dd922a,valeur,13000
1089759,a2877b74-05a6-445d-9774-f701e2dd922a,typeEstimation,Valeur d’acquisition
1310661,5d18f54d-756d-49f2-8f87-3685afef1e82,id,CREATION
1310662,5d18f54d-756d-49f2-8f87-3685afef1e82,commentaire,Achat mobilier qui ne sera effectif que le 20....
1310663,5d18f54d-756d-49f2-8f87-3685afef1e82,description,Un APPARTEMENT au cinquième étage gauche ...
1310664,5d18f54d-756d-49f2-8f87-3685afef1e82,valeur,2390000
1310665,5d18f54d-756d-49f2-8f87-3685afef1e82,typeEstimation,Valeur d’acquisition
1734092,06ed80a7-e3a0-491c-b629-8d8fd23617db,id,CREATION
1734093,06ed80a7-e3a0-491c-b629-8d8fd23617db,conservee,false
1734094,06ed80a7-e3a0-491c-b629-8d8fd23617db,description,Lithographies et tableaux
1734095,06ed80a7-e3a0-491c-b629-8d8fd23617db,valeur,15000
1734096,06ed80a7-e3a0-491c-b629-8d8fd23617db,typeEstimation,Évaluation personnelle
1734099,06ed80a7-e3a0-491c-b629-8d8fd23617db,id,CREATION
1734100,06ed80a7-e3a0-491c-b629-8d8fd23617db,commentaire,[Données non publiées]
1734101,06ed80a7-e3a0-491c-b629-8d8fd23617db,conservee,false
1734102,06ed80a7-e3a0-491c-b629-8d8fd23617db,description,Mobilier - Commode
1734103,06ed80a7-e3a0-491c-b629-8d8fd23617db,valeur,10000
1734104,06ed80a7-e3a0-491c-b629-8d8fd23617db,typeEstimation,Évaluation personnelle
2207165,c6736bca-383b-46ad-bb58-d96de44cd7c3,id,CREATION
2207166,c6736bca-383b-46ad-bb58-d96de44cd7c3,description,Pendentif [Données non publiées]
2207167,c6736bca-383b-46ad-bb58-d96de44cd7c3,valeur,12600
2207168,c6736bca-383b-46ad-bb58-d96de44cd7c3,typeEstimation,Valeur d’acquisition
2226078,6c1dfb54-da9c-4863-9bad-afc20fd58a0b,id,CREATION
2226079,6c1dfb54-da9c-4863-9bad-afc20fd58a0b,commentaire,[Données non publiées]
2226080,6c1dfb54-da9c-4863-9bad-afc20fd58a0b,description,Tableau [Données non publiées]
2226081,6c1dfb54-da9c-4863-9bad-afc20fd58a0b,valeur,30000
2226082,6c1dfb54-da9c-4863-9bad-afc20fd58a0b,typeEstimation,demande à expert octobre 2018
2226358,dd48331d-4162-445f-bdfd-34c5aa0f589e,id,CREATION
2226359,dd48331d-4162-445f-bdfd-34c5aa0f589e,commentaire,[Données non publiées]
2226360,dd48331d-4162-445f-bdfd-34c5aa0f589e,description,Tableau [Données non publiées]
2226361,dd48331d-4162-445f-bdfd-34c5aa0f589e,valeur,30000
2226362,dd48331d-4162-445f-bdfd-34c5aa0f589e,typeEstimation,demande à expert octobre 2018

bienEtrangerDto  
comptesBancaireDto  
fonctionBenevoleDto  
fondDto  
immeubleDto

In [104]:
bienEtrangerDto = creation_table(chemins='bienEtrangerDto/items/', champs_levier='id')

bienEtrangerDto.head()

Table bienEtrangerDto créée

100%|████████████████████████████████████████████████████████████████████████████| 232/232 [00:00<00:00, 228529.48it/s]

Table bienEtrangerDto créée, avec 37 lignes et 9 colonnes.
Les colonnes : Index(['id_declaration', 'idbienEtrangerDto', 'commentaire', 'conservee',
       'description', 'id', 'localisation', 'nature', 'valeur'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idbienEtrangerDto,commentaire,conservee,description,id,localisation,nature,valeur
0,433,2,[Données non publiées],false,"401(K), plan d'épargne retraite herbergé par l...",CREATION,[Données non publiées],Compte d'épargne,89561
1,433,3,[Données non publiées],NaN,NaN,CREATION,[Données non publiées],Compte courant,1681
2,617,35,NaN,NaN,compte à vue,CREATION,[Données non publiées],Compte courant,219
3,617,36,NaN,NaN,Garantie locative,CREATION,[Données non publiées],Livret vert ING,1954
4,899,0,[Données non publiées],false,"401(K), plan d'épargne retraite herbergé par l...",CREATION,[Données non publiées],Compte d'épargne,89561

In [105]:
comptesBancaireDto = creation_table(chemins='comptesBancaireDto/items/', champs_levier='id')

comptesBancaireDto.head()

Table comptesBancaireDto créée

100%|███████████████████████████████████████████████████████████████████████████| 4430/4430 [00:00<00:00, 34903.82it/s]

Table comptesBancaireDto créée, avec 661 lignes et 11 colonnes.
Les colonnes : Index(['id_declaration', 'idcomptesBancaireDto', 'commentaire', 'conservee',
       'etablissement', 'id', 'label', 'numeroCompte', 'titulaire',
       'typeCompte', 'valeur'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idcomptesBancaireDto,commentaire,conservee,etablissement,id,label,numeroCompte,titulaire,typeCompte,valeur
0,251,195,NaN,NaN,CEIDF- [Données non publiées],CREATION,NaN,[Données non publiées],Dujols Dominique,Livret A,2201
1,251,196,NaN,NaN,CEIDF- [Données non publiées],CREATION,NaN,[Données non publiées],Dujols Dominique,LDD,33
2,251,197,NaN,NaN,CEIDF- [Données non publiées],CREATION,NaN,[Données non publiées],Dominique DUJOLS,LEL,306
3,251,198,solde au 27 janvier 2022,NaN,CEIDF- [Données non publiées],CREATION,NaN,[Données non publiées],Dujols Dominique,Compte courant,113
4,251,199,NaN,NaN,CEIDF- [Données non publiées],CREATION,NaN,[Données non publiées],Dujols Dominique,Compte espèces-PEA Numéraire,2

In [106]:
fonctionBenevoleDto = creation_table(chemins='fonctionBenevoleDto/items/', champs_levier='id')

fonctionBenevoleDto.head()

Table fonctionBenevoleDto créée

100%|██████████████████████████████████████████████████████████████████████████| 17022/17022 [00:02<00:00, 8349.40it/s]

Table fonctionBenevoleDto créée, avec 4752 lignes et 8 colonnes.
Les colonnes : Index(['id_declaration', 'idfonctionBenevoleDto', 'commentaire', 'conservee',
       'descriptionActivite', 'id', 'label', 'nomStructure'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idfonctionBenevoleDto,commentaire,conservee,descriptionActivite,id,label,nomStructure
0,3,1821,NaN,true,Présidente,CREATION,NaN,Petites cités de caractère de Bretagne
1,3,1822,NaN,true,Présidente,CREATION,NaN,Petites cités de caractère de France
2,3,1823,NaN,true,Vice-présidente et trésorière,CREATION,NaN,France Patrimoines et Territoires d’Exception
3,4,2590,compétence du Département,false,directrice d'une association quiaccompagne les...,CREATION,NaN,directrice du CIDFF (centre d'information sur ...
4,7,1478,Voir rubrique 3 (participations à des organes ...,NaN,Présidente,CREATION,NaN,Orchestre français des jeunes

In [107]:
fondDto = creation_table(chemins='fondDto/items/', champs_levier='id')

fondDto.head()

Table fondDto créée

100%|██████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<?, ?it/s]

Table fondDto créée, avec 6 lignes et 12 colonnes.
Les colonnes : Index(['id_declaration', 'idfondDto', 'actif', 'commentaire', 'conservee',
       'description', 'endettement', 'id', 'label', 'nature', 'resultatFiscal',
       'valeur'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idfondDto,actif,commentaire,conservee,description,endettement,id,label,nature,resultatFiscal,valeur
0,499,2,NaN,deux comptes bancaires professionnels : --- BN...,false,kinésithérapie : activité libérale exercée par...,NaN,CREATION,Entrée dans le patrimoine,Clientèle,67214,NaN
1,1604,0,NaN,deux comptes bancaires professionnels : --- BN...,false,kinésithérapie : activité libérale exercée par...,NaN,CREATION,Entrée dans le patrimoine,Clientèle,67214,NaN
2,3424,4,5000,Activité mise en sommeil depuis ma nomination ...,NaN,Activité de conseil,0,CREATION,NaN,Clientèle,5306,0
3,4825,1,NaN,deux comptes bancaires professionnels : --- BN...,false,kinésithérapie : activité libérale exercée par...,NaN,CREATION,Entrée dans le patrimoine,Clientèle,67214,NaN
4,5809,3,NaN,NaN,false,kinésithérapie : activité libérale exercée par...,NaN,CREATION,Entrée dans le patrimoine,Clientèle,79590,NaN

In [108]:
immeubleDto = creation_table(chemins='immeubleDto/items/', champs_levier='id')

immeubleDto.head()

Table immeubleDto créée

100%|███████████████████████████████████████████████████████████████████████████| 3656/3656 [00:00<00:00, 42536.53it/s]

Table immeubleDto créée, avec 234 lignes et 20 colonnes.
Les colonnes : Index(['id_declaration', 'idimmeubleDto', 'adresse', 'codePostal',
       'commentaire', 'conservee', 'dateAcquisition', 'droitReel', 'id',
       'label', 'localite', 'nature', 'origine', 'prixAcquisition',
       'prixTravaux', 'quotePart', 'regimeJuridique', 'superficieBati',
       'superficieNonBati', 'valeurVenale'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idimmeubleDto,adresse,codePostal,commentaire,conservee,dateAcquisition,droitReel,id,label,localite,nature,origine,prixAcquisition,prixTravaux,quotePart,regimeJuridique,superficieBati,superficieNonBati,valeurVenale
0,251,58,[Données non publiées],[Données non publiées] (Département : 75),[Données non publiées],NaN,1994,Pleine propriété,CREATION,NaN,[Données non publiées],Appartement,Acquisition,304924,30000,100.0,Bien propre,91,0.0,1210000
1,251,59,[Données non publiées],[Données non publiées] (Département : 12),[Données non publiées],NaN,2015,Usufruit,CREATION,NaN,[Données non publiées],Maison,Acquisition,178000,20000,100.0,Bien indivis,225,0.0,70000
2,251,60,[Données non publiées],[Données non publiées] (Département : 75),[Données non publiées],NaN,2022,Usufruit,CREATION,NaN,[Données non publiées],Garage,Acquisition,30000,NaN,100.0,Bien indivis,0,0.001,12000
3,267,147,[Données non publiées],[Données non publiées] (Département : 64),La valeur vénale déclarée correspond à ma part...,false,2000,Nue-propriété,CREATION,NaN,[Données non publiées],Maison individuelle,Acquisition,600000,NaN,16.0,Bien indivis,310,0.7,150000
4,433,18,[Données non publiées],[Données non publiées] (Département : 42),[Données non publiées],false,2014,Pleine propriété,CREATION,NaN,[Données non publiées],Appartement,Succession,21250,NaN,25.0,Bien indivis,126,0.0,34452

observationInteretDto  
observationPatrimoineDto  
participationFinanciereDto  
passifDto  
valeursEnBourseDto  
valeursNonEnBourseDto  
vehiculeDto

In [110]:
observationInteretDto = creation_table(chemins='observationInteretDto/items/', champs_levier='id')
observationInteretDto.head()

Table observationInteretDto créée

100%|███████████████████████████████████████████████████████████████████████████| 3643/3643 [00:00<00:00, 39194.58it/s]

Table observationInteretDto créée, avec 1810 lignes et 5 colonnes.
Les colonnes : Index(['id_declaration', 'idobservationInteretDto', 'contenu', 'id', 'label'], dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idobservationInteretDto,contenu,id,label
0,2,1345,2019 - impôt prélevé à la source - abattement ...,CREATION,NaN
1,3,683,[Données non publiées],CREATION,NaN
2,9,1134,[Données non publiées],CREATION,NaN
3,16,703,Maire de 2008 à 2014; 33% de l'indice maxMaire...,CREATION,NaN
4,20,1464,[Données non publiées],CREATION,NaN

In [111]:
observationPatrimoineDto = creation_table(chemins='observationPatrimoineDto/items/', champs_levier='id')
observationPatrimoineDto.head()

Table observationPatrimoineDto créée

100%|██████████████████████████████████████████████████████████████████████████████████████████| 62/62 [00:00<?, ?it/s]

Table observationPatrimoineDto créée, avec 31 lignes et 4 colonnes.
Les colonnes : Index(['id_declaration', 'idobservationPatrimoineDto', 'contenu', 'id'], dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idobservationPatrimoineDto,contenu,id
0,251,12,[Données non publiées],CREATION
1,433,2,[Données non publiées],CREATION
2,594,27,[Données non publiées],CREATION
3,899,1,[Données non publiées],CREATION
4,921,18,[Données non publiées],CREATION

In [112]:
participationFinanciereDto = creation_table(chemins='participationFinanciereDto/items/', champs_levier='id')
participationFinanciereDto.head()

Table participationFinanciereDto créée

100%|██████████████████████████████████████████████████████████████████████████| 69712/69712 [00:30<00:00, 2268.76it/s]

Table participationFinanciereDto créée, avec 10988 lignes et 12 colonnes.
Les colonnes : Index(['id_declaration', 'idparticipationFinanciereDto', 'actiConseil',
       'capitalDetenu', 'commentaire', 'evaluation', 'id', 'label',
       'nomOrganisationConseil', 'nomSociete', 'nombreParts', 'remuneration'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idparticipationFinanciereDto,actiConseil,capitalDetenu,commentaire,evaluation,id,label,nomOrganisationConseil,nomSociete,nombreParts,remuneration
0,3,4154,Non,NaN,NaN,12200,CREATION,NaN,NaN,PLURIEL VALEURS 4,151,9097.14 €
1,3,4155,Non,NaN,NaN,4047,CREATION,NaN,NaN,Nouvelles Parts Sociales B,4047,47 €
2,5,2703,NaN,NaN,NaN,1200,CREATION,NaN,NaN,La Coopérative Tiers-Lieux,24,parts sociales de scic non rémunérées
3,5,2704,NaN,NaN,NaN,2400,CREATION,NaN,NaN,Coop'Alpha,48,parts sociales de Scop SA non rémunérées
4,7,3362,NaN,5,Il s'agit d'une SCI immobilière qui loue le bi...,9600,CREATION,NaN,NaN,SCI [Données non publiées],21,88 € en 2020. Environ 600 à 700 € en 2021.

In [113]:
passifDto = creation_table(chemins='passifDto/items/', champs_levier='id')
passifDto.head()

Table passifDto créée

100%|██████████████████████████████████████████████████████████████████████████| 1296/1296 [00:00<00:00, 108085.14it/s]

Table passifDto créée, avec 121 lignes et 14 colonnes.
Les colonnes : Index(['id_declaration', 'idpassifDto', 'adresseCreancier', 'commentaire',
       'conservee', 'datePassif', 'duree', 'id', 'mensualite', 'montant',
       'nature', 'nomCreancier', 'objetDette', 'restantDu'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idpassifDto,adresseCreancier,commentaire,conservee,datePassif,duree,id,mensualite,montant,nature,nomCreancier,objetDette,restantDu
0,251,32,[Données non publiées],NaN,NaN,07/01/2022,24,CREATION,893,21000,Emprunt bancaire,CEIDF,acquisition garage,21000
1,433,10,[Données non publiées],[Données non publiées],NaN,01/12/2018,300,CREATION,3135,825000,Emprunt immobilier,Crédit Agricole,Acquisition immobilière,359365
2,617,120,[Données non publiées],[Données non publiées],NaN,10/09/2019,300,CREATION,2202,577500,emprunt bancaire,caisse d'epargne,acquisition immobilière,564910
3,664,109,[Données non publiées],NaN,NaN,15/10/2018,240,CREATION,638,117140,Crédit Immobilier,Crédit Mutuel,acquisition immobilière,103938
4,899,9,[Données non publiées],[Données non publiées],NaN,01/12/2018,300,CREATION,3135,825000,Emprunt immobilier,Crédit Agricole,Acquisition immobilière,359365

In [201]:
valeursEnBourseDto = creation_table(chemins='valeursEnBourseDto/items/', champs_levier='id')
valeursEnBourseDto.head()

Table valeursEnBourseDto créée

100%|████████████████████████████████████████████████████████████████████████████| 720/720 [00:00<00:00, 180152.65it/s]

Table valeursEnBourseDto créée, avec 103 lignes et 11 colonnes.
Les colonnes : Index(['id_declaration', 'idvaleursEnBourseDto', 'commentaire', 'conservee',
       'etablissement', 'id', 'label', 'naturePlacement', 'numeroCompte',
       'titulaire', 'valeur'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idvaleursEnBourseDto,commentaire,conservee,etablissement,id,label,naturePlacement,numeroCompte,titulaire,valeur
0,251,29,NaN,NaN,CEIDF,CREATION,NaN,PEA,[Données non publiées],Dujols Dominique,40
1,433,7,Souscription le 6/11/2021 de 100 parts du fond...,NaN,NaN,CREATION,NaN,FCPR,[Données non publiées],Jean-Noël BARROT,12032
2,499,83,"la somme de 30874,47 euros correspond à un PEA...",false,BNP [Données non publiées],CREATION,Entrée dans le patrimoine,PEA,[Données non publiées],[Données non publiées],30874
3,499,84,NaN,NaN,BNP [Données non publiées],CREATION,NaN,Compte titre,[Données non publiées],[Données non publiées],140
4,594,77,PEE liquidé pour couvrir la donation et les fr...,NaN,BNP PE & RE,CREATION,NaN,Compte titre,[Données non publiées],[Données non publiées],0

In [115]:
valeursNonEnBourseDto = creation_table(chemins='valeursNonEnBourseDto/items/', champs_levier='id')
valeursNonEnBourseDto.head()

Table valeursNonEnBourseDto créée

100%|████████████████████████████████████████████████████████████████████████████| 283/283 [00:00<00:00, 287545.55it/s]

Table valeursNonEnBourseDto créée, avec 47 lignes et 9 colonnes.
Les colonnes : Index(['id_declaration', 'idvaleursNonEnBourseDto', 'commentaire', 'conservee',
       'denomination', 'droitReel', 'id', 'participation', 'valeurActuelle'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idvaleursNonEnBourseDto,commentaire,conservee,denomination,droitReel,id,participation,valeurActuelle
0,433,1,[Données non publiées],false,Explain (ex Liegey Muller Pons),Pleine propriété,CREATION,0.19,27816
1,594,38,Montant des capitaux propres au 30 septembre 2...,NaN,SARL Domaine de La Grange,Pleine propriété,CREATION,6.666,64252
2,594,39,"Valeur estimée du GFA: Terres agricoles: 31,7 ...",NaN,GFA [Données non publiées],Pleine propriété,CREATION,6.6666,80624
3,617,46,NaN,NaN,AML SARL,Pleine propriété,CREATION,20.0,2473
4,899,0,[Données non publiées],false,Explain (ex Liegey Muller Pons),Pleine propriété,CREATION,0.19,27816

In [116]:
vehiculeDto = creation_table(chemins='vehiculeDto/items/', champs_levier='id')
vehiculeDto.head()

Table vehiculeDto créée

100%|████████████████████████████████████████████████████████████████████████████| 662/662 [00:00<00:00, 220840.63it/s]

Table vehiculeDto créée, avec 97 lignes et 11 colonnes.
Les colonnes : Index(['id_declaration', 'idvehiculeDto', 'anneeAchat', 'commentaire',
       'conservee', 'id', 'label', 'marque', 'nature', 'valeur',
       'valeurAchat'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idvehiculeDto,anneeAchat,commentaire,conservee,id,label,marque,nature,valeur,valeurAchat
0,251,26,2003,NaN,NaN,CREATION,NaN,Peugeot Partner,Terrestre à moteur,2900,13000
1,499,77,2016,NaN,false,CREATION,Entrée dans le patrimoine,renault clio,terrestre à moteur,8500,15000
2,594,73,2016,[Données non publiées],NaN,CREATION,NaN,RENAULT espace IV,Terrestre à moteur,15000,19350
3,594,74,2016,Bateau semi-rigide acheté d'occasion,NaN,CREATION,NaN,Caribe Nautica,Bateau,15000,18500
4,664,60,2015,NaN,NaN,CREATION,NaN,lancia,Terrestre à moteur,300,2000

## Table activCollaborateursDto

In [117]:
activCollaborateursDto = creation_table(chemins='activCollaborateursDto/items/', champs_levier='id')
activCollaborateursDto.head()

Table activCollaborateursDto créée

100%|██████████████████████████████████████████████████████████████████████████| 21414/21414 [00:03<00:00, 6824.99it/s]

Table activCollaborateursDto créée, avec 5938 lignes et 8 colonnes.
Les colonnes : Index(['id_declaration', 'idactivCollaborateursDto', 'commentaire',
       'descriptionActivite', 'employeur', 'id', 'label', 'nom'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idactivCollaborateursDto,commentaire,descriptionActivite,employeur,id,label,nom
0,3,2192,NaN,Collaboratrice en circonscription,NaN,CREATION,NaN,Véronique Bouchet
1,3,2193,NaN,Collaborateur au Sénat,NaN,CREATION,NaN,Romain Brutinaud
2,10,3190,NaN,NaN,NÉANT,CREATION,NaN,PIGNOL Catherine
3,10,3191,conseiller municipal à Villepreux,NaN,NaN,CREATION,NaN,SEVIN-MONTEL Sylvie
4,12,4348,NaN,NaN,néant,CREATION,NaN,Cœur-Joly Marylène

## Ressources activConsultantDto

In [158]:
def id_table2(nom_table, lettre_id_table_mere):

    # ajout de l'id de la table
    ids_table = []
    champs_table = []

    # creation de l'id de la table, qui s'incrémente à chaque nouvel élément, c'est à dire à chaque 'champs_repere_nouvelle_ligne'
    for element in tqdm(nom_table['champs'].values):
        champs_table.append(element)
        i = f'{lettre_id_table_mere}{champs_table.count("id") - 1}'
        ids_table.append(i)

    nom_table[f'id_activite'] = ids_table

    return nom_table

In [159]:
def creation_table_ressources(chemins, lettre_id_table_mere, id_ressource_max=ressources['id_ressource'].max()):
    
    # conditions de mapping entre le chemin xml et les champs de la table en cours
    mask_champs_table = (data3['chemins'].str.contains(chemins, na=False))

    champs_table = data3[mask_champs_table]['chemins'].unique()

    # creation de la table
    table = data3[data3['chemins'].isin(champs_table)][['id_declaration', 'champs', 'valeurs']]
    
    # nom tableau
    nom_tableau = chemins.replace('/items/', '')

    # créer l'id de la table, qui s'incremente par rapport à un champs levier
    table = id_table2(nom_table=table, lettre_id_table_mere=lettre_id_table_mere)

    # suppression des colonnes qui ne sont pas des ressources
    table = table[table['champs'].isin(['annee', 'montant'])]
    
    # ajout de l'id_ressources
    ids_ressources2 = []
    champs_ressources2 = []

    
    # creation de l'id_ressources, qui s'incrémente à chaque nouvelle année
    for element in tqdm(table['champs'].values):
        champs_ressources2.append(element)
        i = id_ressource_max + champs_ressources2.count("annee")
        ids_ressources2.append(i)

    # creation de la colonne id_ressources dans ressources, en tant que clé primaire
    table['id_ressource'] = ids_ressources2
    
    
    # suppression des doublons
    table = table.drop(table[table.duplicated(subset=['id_declaration',
                                                             'champs', f'id_activite', 'id_ressource'], keep=False)].index)

    # pivot de la table ressources
    table = table.pivot(index=['id_declaration', f'id_activite', 'id_ressource'],
                                              columns='champs', values='valeurs').reset_index()

    # encodage id_declaration
    table['id_declaration'] = encoder_id_declaration.transform(table['id_declaration'])

    return table

In [160]:
ressources3 = creation_table_ressources(chemins='activConsultantDto/items/', lettre_id_table_mere='c',
                          id_ressource_max=ressources['id_ressource'].max())

ressources3.head()

100%|██████████████████████████████████████████████████████████████████████████| 18122/18122 [00:02<00:00, 8454.67it/s]
100%|███████████████████████████████████████████████████████████████████████████| 9084/9084 [00:00<00:00, 15532.08it/s]

champs  id_declaration id_activite  id_ressource annee montant
0                    5        c332        381128  2020     188
1                    5        c332        381129  2021   4 648
2                    9        c859        382964  2014   15286
3                    9        c859        382965  2015   17228
4                    9        c859        382966  2016   26424

In [162]:
ressources3.shape

(4542, 5)

## Ressources activProfCinqDerniereDto

In [161]:
ressources4 = creation_table_ressources(chemins='activProfCinqDerniereDto/items/', lettre_id_table_mere='p',
                          id_ressource_max=ressources3['id_ressource'].max())

ressources4.head()

100%|█████████████████████████████████████████████████████████████████████████| 189099/189099 [03:41<00:00, 855.00it/s]
100%|████████████████████████████████████████████████████████████████████████| 101200/101200 [01:12<00:00, 1403.16it/s]

champs  id_declaration id_activite  id_ressource annee montant
0                    0       p3950        399330  2020   25867
1                    1      p11886        429198  2015    6362
2                    1      p11886        429199  2016    6698
3                    1      p11886        429200  2017    7425
4                    1      p11886        429201  2018    1891

In [163]:
ressources4.shape

(50607, 5)

## Concaténation des 4 dataframes ressources

In [164]:
ressources = pd.concat((ressources1, ressources2), axis=0)
ressources.head()

   id_declaration id_activite  id_ressource  annee montant
0               0       m8012         34173   2020    6556
1               0       m8013         34174   2020    3180
2               2      m21205         89421   2012       0
3               2      m21205         89422   2013    7200
4               2      m21205         89423   2014    5820

In [165]:
ressources = pd.concat((ressources, ressources3), axis=0)
ressources.head()

   id_declaration id_activite  id_ressource annee montant
0               0       m8012         34173  2020    6556
1               0       m8013         34174  2020    3180
2               2      m21205         89421  2012       0
3               2      m21205         89422  2013    7200
4               2      m21205         89423  2014    5820

In [166]:
ressources.shape

(329413, 5)

In [167]:
ressources = pd.concat((ressources, ressources4), axis=0)
ressources.head()

   id_declaration id_activite  id_ressource annee montant
0               0       m8012         34173  2020    6556
1               0       m8013         34174  2020    3180
2               2      m21205         89421  2012       0
3               2      m21205         89422  2013    7200
4               2      m21205         89423  2014    5820

In [168]:
ressources.shape

(380020, 5)

In [170]:
# export ressources entier
ressources.to_csv(folder_export + 'ressources.csv', index=False)

## Table sciDto

In [195]:
def creation_table2(chemins, champs_levier):

    # chemins de la table
    mask_champs_table = (data3['chemins'].str.contains(chemins, na=False)) & ~(data3['chemins'].str.contains('immeublesSci/', na=False))
    
    # champs associés au chemin
    champs_table = data3[mask_champs_table]['chemins'].unique()
    
    # creation de la table
    table = data3[data3['chemins'].isin(champs_table)][['id_declaration', 'champs', 'valeurs']]
    print(f"Table {chemins.replace('/items/', '')} créée")
    
    # encodage id_declaration
    table['id_declaration'] = encoder_id_declaration.transform(table['id_declaration'])
    

    # créer l'id de la table, qui s'incremente par rapport à un champs levier
    table = id_table(nom_table=table, champs_levier=champs_levier)
    
    
    # supression des doublons
    table = table.drop(table[table.duplicated(subset=['id_declaration','champs', 'id_table'], keep='last')].index)

    # pivot table
    table = table.pivot(index=['id_declaration', 'id_table'], columns='champs', values='valeurs').reset_index()
    
    # renommage id_table
    table = table.rename(columns={'id_table': f"id{chemins.replace('/items/', '')}"})
    
    print(f"Table {chemins.replace('/items/', '')} créée, avec {table.shape[0]} lignes et {table.shape[1]} colonnes.")
    print(f"Les colonnes : {table.columns}")    
    nom_tableau = chemins.replace('/items/', '')
    
    # export en csv
    table.to_csv(folder_export + f'{nom_tableau}.csv', index=False)
    print('Fichier exporté')
    
    return table

In [200]:
sciDto = creation_table2(chemins='sciDto/items/', champs_levier='id')
sciDto.head()

Table sciDto créée

100%|████████████████████████████████████████████████████████████████████████████| 446/446 [00:00<00:00, 444548.38it/s]

Table sciDto créée, avec 58 lignes et 11 colonnes.
Les colonnes : Index(['id_declaration', 'idsciDto', 'autreActif', 'capitalDetenu',
       'commentaire', 'conservee', 'denomination', 'droitReel', 'id', 'passif',
       'valeur'],
      dtype='object', name='champs')
Fichier exporté

champs,id_declaration,idsciDto,autreActif,capitalDetenu,commentaire,conservee,denomination,droitReel,id,passif,valeur
0,251,11,néant,5.8,NaN,NaN,[Données non publiées],Usufruit,CREATION,néant,9600
1,267,27,NaN,16.0,La SCI [Données non publiées] gère ...,false,[Données non publiées],Nue-propriété,CREATION,NaN,150000
2,433,4,Disponibilités : 1164 euros (au 31/12/2020),32.5,30 % en pleine propriété. 10 % en indivision ...,false,[Données non publiées],Pleine propriété,CREATION,Compte courant d'associés; valeur recouvrable ...,1
3,664,30,compte bancaires crédit Mutuel crédit Agricole,29.0,SCI [Données non publiées] Patricia...,false,[Données non publiées],Pleine propriété,CREATION,Emprunt Crédit Agricole 156472€ 83071€ Emprunt...,254717
4,664,31,NaN,25.0,NaN,NaN,[Données non publiées],Pleine propriété,CREATION,Emprunt Crédit Agricole 352391€,250

### Table immeublesSci

In [214]:
def id_table3(nom_table):

    # ajout de l'id de la table
    ids_table = []
    champs_table = []

    # creation de l'id de la table, qui s'incrémente à chaque nouvel élément, c'est à dire à chaque 'champs_repere_nouvelle_ligne'
    for element in tqdm(nom_table['chemins'].values):
        champs_table.append(element)
        i = champs_table.count("sciDto/items/items/motif/id") - 1
        ids_table.append(i)

    nom_table[f'id_sciDto'] = ids_table

    return nom_table

In [215]:
def creation_table_immeubles(chemins):
    
    # conditions de mapping entre le chemin xml et les champs de la table en cours
    mask_champs_table = (data3['chemins'].str.contains(chemins, na=False))

    champs_table = data3[mask_champs_table]['chemins'].unique()

    # creation de la table
    table = data3[data3['chemins'].isin(champs_table)][['id_declaration', 'chemins', 'champs', 'valeurs']]
    
    # nom tableau
    nom_tableau = chemins.replace('/items/', '')

    # créer l'id de la table, qui s'incremente par rapport à un champs levier
    table = id_table3(nom_table=table)

    # suppression des colonnes qui ne sont pas des immeubles
    table = table[table['chemins'].str.contains('immeublesSci/', na=False)]
    
    # ajout de l'id_immeuble
    ids_immeuble2 = []
    champs_immeuble2 = []

    
    # creation de l'id_immeuble, qui s'incrémente à chaque nouvelle année
    for element in tqdm(table['chemins'].values):
        champs_immeuble2.append(element)
        i = champs_immeuble2.count("sciDto/items/items/immeublesSci/immeublesSci/motif/id")
        ids_immeuble2.append(i)

    # creation de la colonne id_immeuble dans immeuble, en tant que clé primaire
    table['id_immeuble'] = ids_immeuble2
    
    table = table.drop(columns='chemins')
    
    
    # suppression des doublons
    table = table.drop(table[table.duplicated(subset=['id_declaration',
                                                             'champs', 'id_sciDto', 'id_immeuble'], keep=False)].index)

    # pivot de la table immeuble
    table = table.pivot(index=['id_declaration', 'id_sciDto', 'id_immeuble'],
                                              columns='champs', values='valeurs').reset_index()

    # encodage id_declaration
    table['id_declaration'] = encoder_id_declaration.transform(table['id_declaration'])

    return table

In [217]:
sciDto_immeubles = creation_table_immeubles(chemins='sciDto/items/')

100%|██████████████████████████████████████████████████████████████████████████| 1346/1346 [00:00<00:00, 112237.24it/s]
100%|████████████████████████████████████████████████████████████████████████████| 900/900 [00:00<00:00, 128808.90it/s]

In [218]:
sciDto_immeubles.shape

(63, 19)

In [219]:
sciDto_immeubles.to_csv(folder_export + 'sciDto_immeubles.csv', index=False)